### ISSUE TITLE
一个奇怪的问题 MAC 全局模式正常 PAC 缺不能用

### ISSUE THREAD

**Issue by ilovebamboo** [Cenmrev/V2RayX#107]
![image](https://user-images.githubusercontent.com/6214084/40970388-030923e0-68ed-11e8-84ca-e795c24234e7.png)

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/40970338-e4bab642-68ec-11e8-9cdb-4a5244e57118.png)

**Comment by Cenmrev** [comment]
检查你的 pac 文件是否语法正确，是否填写了正确的代理端口。或者重置你的pac文件。

**Comment by Jasonix** [comment]
同样遇到这个问题， 重置pac文件无效。
我把pac.js 里面的第一行改了下
var V2Ray = "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;";
然后configure 里面的local socks5 port改成 1080 
pac模式就正常了

**Comment by Chandler-Lu** [comment]
要不看看你电脑上有无别的软件占用了端口？
`lsof -i:1081`

**Comment by ilovebamboo** [comment]
DYJ:~ blackrose$ lsof -i:1081
DYJ:~ blackrose$ lsof -i:1081
DYJ:~ blackrose$

**Comment by ilovebamboo** [comment]
同样遇到这个问题，重置pac文件无效。
我把pac.js里面的第一行改了下
var varRay =“SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;”; 
然后configure里面的本地socks5端口改成1080 
pac模式就正常了 照你说的成功了 我也安装了SSR客户端 不知道是不是这个引起的，要不就是V2RAY的PAC.JS问题 改了就好了。

**Comment by Chandler-Lu** [comment]
在pac模式（没改pac.js之前）下输这个命令什么输出都没有？

**Comment by ilovebamboo** [comment]
是的

**Comment by Cenmrev** [comment]
@ilovebamboo @Jasonix 两位能不能帮忙试一下，
1. 把 pac 文件和 configure 的本地 socks5 端口全都改成 1085，能不能正常用 pac 模式呢？
2. 使用 1081 端口，关掉推出其他所有类似 ssr 的软件，能不能正常使用 pac 模式呢？
3. 如果以上有情况不正常，在命令行里执行`sudo lsof -i:1081` 或者 `sudo lsof -i:1085`，是什么输出？执行`ps -fe | grep v2ray` 是什么输出？以及在 系统设置 -> 网络 -> 高级 -> 代理 -> 自动代理 页面所显示的代理文件URL是什么？

谢谢。

**Comment by Chandler-Lu** [comment]
@ilovebamboo 我把ssr下载下来试了一下。。实在是没有复现，，你看看作者的方法吧～ssr的pac监听的是8081应该是不会有端口冲突这个问题的0.0

**Comment by BppleMan** [comment]
我也遇到这个问题，我的解决方案是，根据configure里面local socks5 port的具体端口值，修改pac.js文件第一行中的端口值

**Comment by BppleMan** [comment]
@MichaelVector 那是因为mac版shadowsocks的gui客户端，第一次启动时，在`~/Library/SystemAgents`目录下放了三个`shadowsockxxxx.xxxx.plist`文件，这个目录是存放用户级用于自启动的守护进程的plist文件，所以你重启之后启动了一个ss-local的客户端，不信可以用`ps -ef|grep ss-local` or `systemctl list|grep shadow`，ss-local占用了1080端口，导致v2ray无法监听该端口，所以此时修改pac文件的端口是毫无用处的，解决办法就是取消shadowsocks客户端的自启动，如果不成功的话，在`~/Library/SystemAgents`目录下删除shadowsocks的相关plist文件，之后重启电脑。但是唯一可以确定的是，在没有端口占用的情况下，pac文件使用的端口必须和v2ray设置的端口保持一致：主要是http\https\socks5的端口

**Comment by MichaelVector** [comment]
@BppleMan 多谢大神指点。
1、首先不管我开没开ss，我都没有看到你说的那个agent的目录呢？
2、ss自启动我已经关了，现在自启v2还是老问题，必须打开一下ss再退出才可以正常上网。
3、端口保证一致，这个没问题的，就是开机自启连不上网

**Comment by BppleMan** [comment]
@MichaelVector 路径写错了，已修改

**Comment by MichaelVector** [comment]
@BppleMan 多谢大神，我删除了你说的plist文件以后重启后，v2自启动就可以正常联网了。再次感谢！
要是什么时候官方的应用程序能加入自动更新和自动更新pac就完美多了，嘿嘿

**Comment by Gabrielvon** [comment]
我也遇到一样的问题。我把上面提到的端口全改成1085了，也还是不行。但是全局模式是一直都可以。请问是什么原因呢？有新的解决方法吗？

**Comment by xiebruce** [comment]
这个问题好像一直都没有解决呀，我现在还是有这个问题，socks5本地端口改成监听了1085，pac.js那里也改成了1085了，unload后重新load core了，也试了重启V2rayX，就是pac不行，全局没任何问题：

macOS: `10.14.4 (18E226)`
V2rayX: `1.5.1 (1278)`

![image](https://user-images.githubusercontent.com/13575500/59026903-1d4d9980-888a-11e9-9e99-819c6c3231a8.png)

![image](https://user-images.githubusercontent.com/13575500/59026938-30606980-888a-11e9-815d-6cee632c4096.png)

![image](https://user-images.githubusercontent.com/13575500/59026970-45d59380-888a-11e9-9010-384b9b7c4f4b.png)

**Comment by alanhe421** [comment]
@BppleMan 
pac.js文件在哪？

**Comment by BppleMan** [comment]
> @BppleMan
> pac.js文件在哪？

pac mode->edit pac

**Comment by bankel** [comment]
> @BppleMan
> pac.js文件在哪？

mac 系统的位置 /Applications/V2rayU.app/Contents/Resources/pac
或者直接 find / -iname "pac.js" 查找

**Comment by dicle80** [comment]
各种方法都用了，依然不行，ocks5 端口全都改成 1085也不行。

**Comment by zxq1002** [comment]
我改了pac文件之后一段时间就不能连了，但是直接连1081代理是没问题，或者reset pac之后也恢复正常

**Comment by 6r6** [comment]
退出所有的客户端。打开shadowsocks，将代理模式改为global模式然后退出，这时候重新打开v2ray，pac模式即可正常。

**Comment by NinoPanic** [comment]
我的版本 1.5.1.
即使pac.js的port 和 configure里的一致也无法使用pac mode.


> > @BppleMan
> > pac.js文件在哪？
> 
> mac 系统的位置 /Applications/V2rayU.app/Contents/Resources/pac
> 或者直接 find / -iname "pac.js" 查找

参考这个回复后在 /Applications/V2rayU.app/Contents/Resources/pac下加了pac.js就可以食用pac了

**Comment by lightingtime** [comment]
> 我的版本 1.5.1.
> 即使pac.js的port 和 configure里的一致也无法使用pac mode.
> 
> > > @BppleMan
> > > pac.js文件在哪？
> > 
> > 
> > mac 系统的位置 /Applications/V2rayU.app/Contents/Resources/pac
> > 或者直接 find / -iname "pac.js" 查找
> 
> 参考这个回复后在 /Applications/V2rayU.app/Contents/Resources/pac下加了pac.js就可以食用pac了

我遇到的情况是将上述路径下一个proxy.js重命名为pac.js起作用

**Comment by TylerDurdenT** [comment]
> 退出所有的客户端。打开shadowsocks，将代理模式改为global模式然后退出，这时候重新打开v2ray，pac模式即可正常。

咦 为啥这样一下子就成了啊

**Comment by mo7cc** [comment]
我今天早上也遇到了这个问题 , 全局模式正常, PAC无法访问 , 后面找到了原因 , pac配置文件和Socks5端口要保持一致

![图片](https://user-images.githubusercontent.com/24769632/75842865-8c055680-5e0c-11ea-98c9-b0109d8f086e.png)

**Comment by haobanz** [comment]
全局模式咋跳过国内的地址啊？

**Comment by ablueday** [comment]
MAC: 10.15.4
V2RayX: 1.5.1
上面提到的方法都试过了，Global 可用，PAC 不可用。

**Comment by zhengdai** [comment]
> MAC: 10.15.4
> V2RayX: 1.5.1
> 上面提到的方法都试过了，Global 可用，PAC 不可用。

我也是，突然有一天不好使

**Comment by lsy076** [comment]
@6r6 已解决，看这里

**Comment by pacsicd** [comment]
我也是碰到这个问题，后来仔细检查了一下，发现是pac.js文件加了一个条目，,用错了，弄成了中文的，改掉后就好了

**Comment by baixiang0101** [comment]
我的是完全退出，然后重启就好了。。。

**Comment by MichaelVector** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你所发的邮件我以收到。我将在工作结束后，尽快给您回复。

**Comment by JunjieLl** [comment]
> @MichaelVector 那是因为mac版shadowsocks的gui客户端，第一次启动时，在`/Users/xxxx/Library/LaunchAgents`目录下放了三个`shadowsockxxxx.xxxx.plist`文件，这个目录是存放用户级用于自启动的守护进程的plist文件，所以你重启之后启动了一个ss-local的客户端，不信可以用`ps -ef|grep ss-local` or `systemctl list|grep shadow`，ss-local占用了1080端口，导致v2ray无法监听该端口，所以此时修改pac文件的端口是毫无用处的，解决办法就是取消shadowsocks客户端的自启动，如果不成功的话，在`/Users/xxxx/Library/LaunchAgents`目录下删除shadowsocks的相关plist文件，之后重启电脑。但是唯一可以确定的是，在没有端口占用的情况下，pac文件使用的端口必须和v2ray设置的端口保持一致：主要是http\https\socks5的端口

感谢🙏

**Comment by MichaelVector** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你所发的邮件我以收到。我将在工作结束后，尽快给您回复。

**Comment by Takdrift** [comment]
我的问题是在自定义PAC里增加了几个域名后出现的，删除掉就恢复正常了，不清楚是什么原因。

**Comment by MichaelVector** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你所发的邮件我以收到。我将在工作结束后，尽快给您回复。

**Comment by allen-davis** [comment]
> 退出所有的客户端。打开shadowsocks，将代理模式改为global模式然后退出，这时候重新打开v2ray，pac模式即可正常。

确实互相影响了，这样可以解决，感谢！

**Comment by MichaelVector** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你所发的邮件我以收到。我将在工作结束后，尽快给您回复。
