### ISSUE TITLE
rules模式或全局模式下，无法访问192.168.*.*等内网地址

### ISSUE THREAD

**Issue by ghost** [Cenmrev/V2RayX#11]
大概是这些地址也走了代理。按道理来讲，这些地址应该过滤掉的。

**Comment by kslr** [comment]
同样也包括了localhost等，期待尽快修复

**Comment by Cenmrev** [comment]
谢谢反馈，我尽量抽空修复。

**Comment by Cenmrev** [comment]
@kslr @kuzmailer  我这边测试了下，全局模式和rules模式访问 localhost 没有问题，如果你们还是不能访问，请详细描述下你们的使用场景。

另外， V2RayX 使用的路由规则和上游的 v2ray-core 的规则是一致的，如果192.168.*.*等内网地址无法访问，请直接向上游项目反馈。

**Comment by kslr** [comment]
hi @Cenmrev 
A-B, A在国内，B在国外。均只修改了uuid，其他都是默认。X客户端使用rules模式。

**Comment by zoakerc** [comment]
@Cenmrev rules模式下访问localhost，展示内容是远程服务器的80端口

**Comment by free1x** [comment]
我也不行，同个项目在手机没问题，应该是规则那些没弄好

**Comment by Cenmrev** [comment]
@free1x 这个问题我毫无头绪，能否分享你的配置文件给我参考下？

**Comment by free1x** [comment]
@Cenmrev 我用的是自带的v2rayx rule模式，这个模式比pac快，但访问192.168.和一些国内网站访问不了。但用pac模式就正常，就是会比v2rayx rule模式慢和国外有些网站访问不了，得自定义pac。考虑支持自动下载更新GFW 规则吗？

**Comment by Hwatu** [comment]
我也遇到了此问题
环境: MacOS 10.13.2
软件: V2rayX  1.2.1
问题描述: 

1. V2rayX 使用的是 V2ray Rules模式.
    在浏览器中可以正常访问192.168.*.*
    在使用maven 私服打包上传时, 遇到访问不了私服地址(域名), 私服地址在/etc/hosts里做了ip映射.

2. 当使用PAC Model时可以正常访问

**Comment by z20690865** [comment]
这个问题还没有解决吗，我现在也有这个问题，访问192.168.*.*不行 通过pac mode是可以的

**Comment by Cenmrev** [comment]
现已经可以手动编辑路由规则，有需要的用户请手动对192.168.*.*等地址设定规则。

**Comment by h00448672** [comment]
【参数设置】中的【路由设置】，找到【预定义规则】，然后选择绕过局域网地址
