### ISSUE TITLE
能否加上在线更新pac文件的功能

### ISSUE THREAD

**Issue by labixiaoshuai** [Cenmrev/V2RayX#111]
现在pac文件的规则比较少，不能在线更新不太方便。

**Comment by ImHUan** [comment]
我是v2rayx开manual，然后用 Proxy SwitchyOmega 这个chrome插件来解决直连 和 代理的配置问题，很好用，分享给你参考

**Comment by Chandler-Lu** [comment]
其实你可以自己手动把gfwlist复制进去就好了，但是使用完整版gfwlist第一个是对性能有影响，第二个是没这么多必要。。
目前基本上主流网站都已经覆盖完全了，最多也就是一些零碎的网站被加进去。以今年1月和最新的gfwlist为例，只更新了113条，所以真的有需要手动添加就好啦
![wx20180612-205020](https://user-images.githubusercontent.com/18322610/41291484-657a21b0-6e82-11e8-992b-aa93895f5cc1.png)

**Comment by labixiaoshuai** [comment]
OK👌
