### ISSUE TITLE
如何从GFWList更新pac?

### ISSUE THREAD

**Issue by Ninzero** [Cenmrev/V2RayX#113]
还是说默认的pac.js就是GFWList?

**Comment by Chandler-Lu** [comment]
暂时没有这个功能，需要更新的话，可以手动更新。GitHub的gfwlist使用base64编码的，解码后，覆盖pac.js里面的
```
{
    "xxxxxx",
}
```
即可。
另外，gfwlist半年才更新100多个条目，有效条目更少，几乎没有更新的必要

**Comment by Ninzero** [comment]
那我能不能问一下为什么WhatsApp的客户端不能联网?是不是因为pac.js是精简版的?

**Comment by Ninzero** [comment]
我研究了一下,只有whatsapp.com和whatsapp.net两个域名,没有ip直连,我加进pac就解决了,建议增加

**Comment by Chandler-Lu** [comment]
嗯～可以用的话是最好了～
