### ISSUE TITLE
第三方客户端收发Gmail需要在pac里添加什么?

### ISSUE THREAD

**Issue by Ninzero** [Cenmrev/V2RayX#114]
目前来说我使用Spark管理邮件,但在pac模式下无法正常收发邮件。

我看了一下全局模式的log, 也看不出有什么我没有添加的域名。

我试过添加smtp.gmail.com和imap.gmail.com, 一方面来说他们本来就是gmail.com的,另一方面来说这也没有解决问题

是我还需要往pac.js添加什么奇怪的域名吗?

连问两个问题实在不好意思,麻烦了

**Comment by Ninzero** [comment]
有可能问一下为什么吗?

**Comment by Chandler-Lu** [comment]
IMAP和SMTP不走pac

**Comment by Ninzero** [comment]
明白了,谢谢

**Comment by alanhe421** [comment]
v2rayx设定为全局模式，仍然mail客户端连接不上gmail，我利用surge做前置代理，确定gmail的连接走了v2ray，但还是连接上上。什么鬼。
![image](https://user-images.githubusercontent.com/9245110/59103253-f0b88100-8960-11e9-86ea-9c393d4278d5.png)
