### ISSUE TITLE
我在网上找了一个vmess链接,解码后,如何配置到v2rayx里面?不知道这些字段和界面对应关系

### ISSUE THREAD

**Issue by 04HzJqw** [Cenmrev/V2RayX#115]
{"v":"2", --不懂
"ps":"CTCGFW-America-CDN", --这是注解
"add":"1.1.1.1", --这是ip,这个信息被我过滤
"port":"443", --这是端口
"id":"e2d4f6da-2688-4086-ac1d-5d1892d3c6b2", --应该是userid吧?
"aid":"0", --alterid?
"net":"ws", --network?
"type":"none", --不懂
"host":"",--不懂
"path":"/auto_change/2b7dc011-0649-487c-9825-2051f72ad38a",--不懂
"tls":"tls" --难道是tls>use tls?

tls>server name: server.cc 需要更改吗?改成什么?

**Comment by Chandler-Lu** [comment]
把v2ray用户手册仔细看一遍吧，都是最基础的配置。而且以你这个解开之后的内容来看是没有服务器地址的。根本用不了

**Comment by 04HzJqw** [comment]
add,port不就是服务器地址吗?信息是我过滤掉了 
可否依据上面的设置,截个图标注一下吗.哪些需要填写,哪些不需要填写?

**Comment by Chandler-Lu** [comment]
。。我还以为别人就是这么写的。都需要填写
