### ISSUE TITLE
默认的加密方式有误，导致下载断流

### ISSUE THREAD

**Issue by skewer** [Cenmrev/V2RayX#116]
我的v2ray配置的是vmess+kcp，下载大文件时候断流，但手机上不会，通过搜索发现了这个问题。供各位参考。

https://github.com/v2ray/v2ray-core/issues/194最后一个评论
“发现一种可能的断流原因

服务端配置的时候没有给 user 配置 security，这时应该默认的 security 为 auto，按照文档描述运行框架为amd64和s390x时为aes-128-gcm加密方式，其他情况则为chacha20-poly1305加密方式

客户端使用 v2rayx，默认的 security 为 aes-128-cfb

其他参数配置正确的情况下，如果客户端 security 配置为 aes-128-cfb 时，可以正常连接使用，但是下载大文件会断流；客户端 security 修改为 aes-128-gcm 则一切正常。”

**Comment by Chandler-Lu** [comment]
128-cfb较chacha和128-gcm而言的确有更多被干扰的可能，但并不是默认加密方式有误啦。可以根据自己情况修改，一般建议auto

**Comment by Kylejustknows** [comment]
确实有这个问题！！

因国内家人住院，我回国3个月在医院陪护，遇到随机断流，有时几分钟有时几天。在病房花了大量时间几百小时耐心调试v2ray。 非常确定的测试结论如下：

至2018年10月版，如果服务器的加密用auto，客户端必须使用128-gcm。客户端使用另两个协议或者用auto都会不定期断流(ws+tls)。 而且mux啊缓存啊怎么设置都不会断流。

某些运营商已经能监测kcp，一旦使用很快被临时封ip，几天后解除。某些运营商不管。
