### ISSUE TITLE
使用1.2.1 版本无法启动v2ray服务，但是在1.1.1版本以及以下的没有问题，已经确定配置文件是没有问题的

### ISSUE THREAD

**Issue by zhoubo6419** [Cenmrev/V2RayX#118]
在新版本要设置啥东西不，我是直接下载的安装包

**Comment by Chandler-Lu** [comment]
#117 试试这个？

**Comment by zhoubo6419** [comment]
@Chandler-Lu  您好，我安装过你的中文化的版本 是没有问题，请问一下你是编译的那个版本，但是我只要安装作者的1.2.1和1.2.0就有问题，我开始以为是我编译的问题，后来我去下载作者已经打包好的还是不行。
znsdeiMac:~XXX$ lsof -i | grep -i 8070
V2RayX    55057 syslinc_dabo    4u  IPv4 0xf3bda3d1b008a47      0t0  TCP *:8070 (LISTEN)
V2RayX    55057 syslinc_dabo    6u  IPv6 0xf3bda3d1c471b3f      0t0  TCP *:8070 (LISTEN)

**Comment by zhoubo6419** [comment]
@Chandler-Lu 我的界面倒是没有问题 都可以操作

**Comment by Chandler-Lu** [comment]
emmm你是不是认错人了？我没有什么中文化的版本啊～
想问一下无法启动v2ray服务是什么表现？另外可以考虑完整卸载老版本（删除以下文件或目录）然后重新安装，试试能否正常使用
```
/Applications/V2RayX.app
/Users/用户名/Library/Preferences/cenmrev.V2RayX.plist
/Users/用户名/Library/Application Support/V2RayX
/Library/Application Support/V2RayX
```

**Comment by zhoubo6419** [comment]
@Chandler-Lu  不好意思 不是你😂 嗯嗯 好的 多谢了 我试试
