### ISSUE TITLE
请问有OSX的编译好的最新版本吗？

### ISSUE THREAD

**Issue by ttaowang** [Cenmrev/V2RayX#120]
感谢！

**Comment by Chandler-Lu** [comment]
https://github.com/Cenmrev/V2RayX/releases
别做伸手党谢谢

**Comment by ttaowang** [comment]
抱歉，技术小白。昨天我试着通过搜索引擎解决这个问题，下载release ，放到application
目录，但提示程序无法运行，怀疑权限问题，就学着用终端改权限，也没成功。实在没法才发帖求助，或者有什么指导封装的入门贴？

Chandler-Lu <notifications@github.com>于2018年7月22日 周日上午8:30写道：

**Comment by Chandler-Lu** [comment]
你是不是下错了release，你应该下V2RayX.app.zip这个，然后解压运行

**Comment by Cenmrev** [comment]
@ttaowang 右键图标->打开。可行吗？

**Comment by ttaowang** [comment]
一样的问题

Cenmrev <notifications@github.com>于2018年7月22日 周日下午1:04写道：

**Comment by ttaowang** [comment]
对了，我还试着安装了0.87，然后想把新版本的源文件覆盖过去，也没成功。

Wang Tao <ttaowang@gmail.com>于2018年7月22日 周日下午5:40写道：

**Comment by Chandler-Lu** [comment]
所以你的系统版本是什么

**Comment by ttaowang** [comment]
操作系统？我之前给你的截图里有，10.13.3，V2RayX有问题的这个是1.2.1吧？最新的那个。

Chandler-Lu <notifications@github.com>于2018年7月22日 周日下午5:49写道：

**Comment by Chandler-Lu** [comment]
你的图是不是没发上来，并没有图～

**Comment by ttaowang** [comment]
所以通过邮件无法将图上传到这里……刚刚发现这个问题
