### ISSUE TITLE
使用tls之后trustd的CPU占用率100%

### ISSUE THREAD

**Issue by cbdog94** [Cenmrev/V2RayX#121]
不使用tls的时候正常。单独使用v2ray-core不会出现这种问题。
v2rayx版本1.2.1
macOS版本10.13.6

**Comment by Cliffhou** [comment]
同時使用tls和mux 可暫時解決問題

**Comment by Cliffhou** [comment]
更新到最新的3.35 core 可解決問題

**Comment by cbdog94** [comment]
多谢 @Cliffhou ，升级3.35解决问题。
