### ISSUE TITLE
用v2ray-core在终端里运行正常，但用这个app就没法代理，有同样情况的吗 10.13.5

### ISSUE THREAD

**Issue by jsnjycwyz** [Cenmrev/V2RayX#122]
下载最新版的core直接在终端里可以运行，网页也正常，但用这个app导入json闪退，然后手动填好后无法上网，只有上传流量没有下载流量，有没有解决办法，已经替换成最新的内核，系统10.13.5

**Comment by Chandler-Lu** [comment]
先确认一下你手动填写的信息对不对，多半是填错了

**Comment by jsnjycwyz** [comment]
肯定是对的啊，我导入json一点OK就闪退，我就导入后一项一项复制然后把导入到那个删掉点OK才行

**Comment by Chandler-Lu** [comment]
可以的话建议把json私发给我，chandler.lu1997@gmail.com

**Comment by jsnjycwyz** [comment]
我刚刚就是测试下v2ray。。然后现在服务器已经删了😂反正在log里什么也没看到，然后运行的时候只有上行流量在变动，下行流量一直就1、2kb

**Comment by Chandler-Lu** [comment]
额，不知道你是否使用的是使用官方脚本安装v2ray时生成的json，如果是那个json理论上不会有问题，毕竟你直接用core是正常的。如果是用所谓第三方一件脚本安装的话，无法保证

**Comment by jsnjycwyz** [comment]
嗯，我用的是这个
bash -c "$(curl -fsSL https://raw.githubusercontent.com/tracyone/v2ray.fun/master/install.sh)"
导出后用core能运行，在这个v2rayx app里点ok就闪退，而且配制敲进去也不能上网

**Comment by Chandler-Lu** [comment]
如果你下一次再试v2ray然后能重现这个问题的话可以把json发上来看一下～因为你现在木有json文件，也很难复现这个问题呐～

**Comment by jsnjycwyz** [comment]
我有失效的那个json可以吗😂，服务器已经关了用不了了的

**Comment by Chandler-Lu** [comment]
可以发来我看一下

**Comment by jsnjycwyz** [comment]
已发

**Comment by jsnjycwyz** [comment]
已接近，由于第三方脚本导出的json不支持，要手动填写参数，特别是transport settings里的也要记得改，感谢 @Chandler-Lu 的耐心解答，图也是ta提供的！
![0eba90d4-d0fe-448f-ae18-cde37d29ef1f](https://user-images.githubusercontent.com/11692160/43361815-c0029fcc-930d-11e8-8e85-00272a065960.jpeg)
