### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by MichaelVector** [Cenmrev/V2RayX#124]
非常喜欢对mac系统做的这个app，感谢付出，有几点建议
1、希望可以支持自动更新。
2、希望可以添加扫描二维码导入的选项。
3、希望可以增加对原版ss或者ssr的功能入口（可以兼容老版ss或者ssr）。
4、自动更新PAC文件。
5、增加中文选项（语言选项）。
6、增加对服务器测速和延迟的选项。关于这点，原先的ss或者ssr出现大部分TCP阻断，可以ping通但不能用ssh工具连接，如果能增加对服务器的ping测试和TCP的连接测试更好不过，比如说https://ipcheck.need.sh   这个网站可以针对两项进行测试，如果能添加到程序里就完美了。
再次感谢对此项目付出的战友！

**Comment by Cenmrev** [comment]
谢谢你的建议，1456理论上可以做但需要我有空闲时间，3的话原版ss已经支持，但需要自己写config.json，然后导入，ssr的支持比较麻烦，因为v2ray-core并不支持ssr。2的话，因为v2ray官方没有出二维码的标准，现在其他客户端的二维码基本是他们自己搞的标准。

**Comment by PromiseNev** [comment]
其实希望能出服务器信息导出导入的功能!

**Comment by zmj1368** [comment]
vmess://eyJ2IjogIjIiLCJwcyI6ICIyMzNibG9nX3YycmF5XzE4NS4yMi4xNTQuMjI5IiwiYWRkIjogIjE4NS4yMi4xNTQuMjI5IiwicG9ydCI6ICI1NjMwMiIsImlkIjogIjBlMzBmZGJjLTMxOGItNGE4Ny1hZjFlLWRlZjQzYmZhNmRmZiIsImFpZCI6ICIyMzMiLCJuZXQiOiAidGNwIiwidHlwZSI6ICJub25lIiwiaG9zdCI6ICIiLCJwYXRoIjogIiIsInRscyI6ICIifQ==
请问能对这种信息进行支持吗
