### ISSUE TITLE
谁帮忙科谱下V2ray Rules PacModel GlobalModel ManualModel区别及日常使用

### ISSUE THREAD

**Issue by Hwatu** [Cenmrev/V2RayX#127]
V2ray Rules 和globleModel 感觉一模一样啊. ManualModel完全不代理, Pac就是常规Pac没什么好说的

**Comment by MichaelVector** [comment]
感觉是PAC现在还很简陋，打开看下pac就知道了

**Comment by Chandler-Lu** [comment]
“科普”。。发问题前麻烦先解决一下语文问题。。

- v2ray rules是由`geoip.dat`和`geosite.dat`两个文件控制，本软件会将`geosite:cn`和`geoip:cn`（中国域名和中国ip）直连，除此之外走代理
- pac模式不解释，楼上说pac简陋的，可以自行更新pac文件，写法依照pac的格式自己加就可以了
- manual 顾名思义，手动模式，不配置系统级代理。可以自行使用浏览器插件或其他软件配置需要的代理模式
- globle 全局模式，不管哪国域名，不管哪国ip，统统走代理

**Comment by Hwatu** [comment]
谢谢

**Comment by puppet1an** [comment]
我想问一下 ，chrome浏览器要同步书签的话 ，应该选pac 还是 v2ray rules 代理？ 这个地方我没完全理解，chrome浏览器是一个软件 ，我浏览网页时候一般选择的pac 代理，开pac代理的时候火狐浏览器也能访问国外网站，但是浏览器安装的其他插件要同步书签要同步的话 ，应该选v2ray rules吗？ 不可能选全局globel吧

**Comment by Chandler-Lu** [comment]
> 我想问一下 ，chrome浏览器要同步书签的话 ，应该选pac 还是 v2ray rules 代理？ 这个地方我没完全理解，chrome浏览器是一个软件 ，我浏览网页时候一般选择的pac 代理，开pac代理的时候火狐浏览器也能访问国外网站，但是浏览器安装的其他插件要同步书签要同步的话 ，应该选v2ray rules吗？ 不可能选全局globel吧

对于chrome来说，pac以列表来分流，列表内名单走代理。rules以ip来做分流，中国ip之外的走代理，仅此而已。

**Comment by c382893923** [comment]
请教一下，那我是不是可以选择mannul mode，然后配合浏览器的SwitchOmega插件进行GFWList配置，或者直接用pac模式，不设置浏览器代理。

**Comment by Chandler-Lu** [comment]
@c382893923 可以，但是说实话不太理解用manual的意义- -
