### ISSUE TITLE
自定义端口时 geosite.dat 失效

### ISSUE THREAD

**Issue by sagiwei** [Cenmrev/V2RayX#128]
当自定义代理端口时，例如修改 HTTP proxy 端口为 1087，sock5 proxy 端口为 1086 时，Rules 模式下，geosites.dat 的 routing 效果失效，全部都会走代理请求

**Comment by Chandler-Lu** [comment]
![wx20180804-073838](https://user-images.githubusercontent.com/18322610/43669927-7fe9e1ce-97b9-11e8-9939-bce1d182a3f3.png)
我这里并没有问题，建议检查一下原先是否有其他软件工作在1087，1086端口上
