### ISSUE TITLE
新增Server点击OK，客户端就闪退

### ISSUE THREAD

**Issue by herozhang** [Cenmrev/V2RayX#129]
环境：macOS 10.13.6
V2RayX版本：1.2.1

复现步骤：
1. 点击Configure菜单
2. 新增一个Server
3. 点击OK
4. 客户端闪退，并且刚才添加的Server并未保存

**Comment by Cenmrev** [comment]
Server 的内容填写的是什么呢？当前选择的是什么模式(global/rules/pac/manual)？
请在终端里面运行`defaults read cenmrev.V2RayX`后再试一下
