### ISSUE TITLE
Do not update system proxy settings automatically

### ISSUE THREAD

**Issue by balthild** [Cenmrev/V2RayX#13]
I use proxifier to manage proxies for specified app. 
Please provide an option to disable/enable system proxy settings, like Manual Mode in ShadowsocksX-NG.

**Comment by netcookies** [comment]
+1

**Comment by KyonLi** [comment]
+1

**Comment by mrtanuky** [comment]
+1

**Comment by Cenmrev** [comment]
Added. Report bugs please if you find one.

https://github.com/Cenmrev/V2RayX/releases/tag/v0.7.7

**Comment by balthild** [comment]
Great works!
