### ISSUE TITLE
希望支持不同模式下的快捷键切换

### ISSUE THREAD

**Issue by herozhang** [Cenmrev/V2RayX#130]
通过按快捷键，可以快速设定到诸多代理模式中的一种
V2Ray Rules
Pac Modes
等等

再加上V2Ray本身的开关。

**Comment by Cenmrev** [comment]
全局快捷键容易和其他软件的快捷键造成冲突，弊大于利，短期内不打算添加这个功能。

**Comment by smart-z** [comment]
> 全局快捷键容易和其他软件的快捷键造成冲突，弊大于利，短期内不打算添加这个功能。

快捷键可以默认不启用，可以自由设置，完全不会弊大于利，不明白怎么得出这样的结论。
