### ISSUE TITLE
Version 1.2.1 (285)版本无法切换节点

### ISSUE THREAD

**Issue by PromiseNev** [Cenmrev/V2RayX#132]
我添加了好多节点,然后,切换节点,界面显示切换到新的节点,但是实际上没有变,还是以前的节点
这个是什么问题呢?

**Comment by PromiseNev** [comment]
@Cenmrev  我是因为要上日本的网站,有地区IP限制,所以我就从我的HK切换到日本,然后,上日本的网站,还是上不去,然后我就登陆https://en.ipip.net/查看我的IP,发现节点还是我上个节点的IP,没有切换到我的日本节点.

**Comment by Chandler-Lu** [comment]
麻烦按照楼上``view current config.json``查看一下实际配置是否切换

**Comment by PromiseNev** [comment]
看了一下,当前的config,是切换了的,但是.....上网,还是HK的节点,日本的网站是上不去的,然后查看ipip网站,显示的也是hk的ip.不是我日本的ip

**Comment by PromiseNev** [comment]
而且我现在试了一下,又能切换成功了,这个目前的症状看起来是偶发的bug.

**Comment by gzlock** [comment]
1. 路由器的梅林固件的科学上网插件已经确定关闭
2. 在用V2rayX 1.5.1 release版本
2. Unload Core再重新打开V2rayX问题还在
3. 重启mac再打开V2rayX，问题还在

问题情况：
试过切换美国，日本，台湾，澳门节点（config.json也显示了对应的节点域名）
![image](https://user-images.githubusercontent.com/2311740/54474391-02d1ca00-481f-11e9-90f3-2120a515411f.png)
但ip还是香港的（全局模式，所以对百度也生效）
![image](https://user-images.githubusercontent.com/2311740/54474396-1da43e80-481f-11e9-985d-177cfbbf2d0c.png)

问题还存在，找不到解决方法
