### ISSUE TITLE
问题：Version 1.2.1 (285)配置ws+tls时，编辑 WebSocket 的 headers 时软件报错

### ISSUE THREAD

**Issue by yfu1900** [Cenmrev/V2RayX#133]
描述：在配置Version 1.2.1 (285) 的ws+tls时，点开transport settings - WebSocket，编辑 path 为 /download，编辑 headers 的 host 为 bac.cc ，点击OK后，软件提示 "Error in parsing customized WebSocket headers!"

![001](https://user-images.githubusercontent.com/19819142/43877069-8c6c8360-9bca-11e8-9987-8ad970c411ec.png)

于是，通过编辑本地config.json时，发现 path 多了一个"\"，显示"\/download"， 如下图：

![004](https://user-images.githubusercontent.com/19819142/43877209-2e91d3f2-9bcb-11e8-9faa-622bf84e00db.png)

手动更改 path、headers后，导入config.json，配置通过。

问题：
1. 无法通过图形界面修改headers值；
2. 图形界面输入的path值，在实际config.json中多出一个字符“\”。

请验证。

**Comment by Cenmrev** [comment]
第二个问题，config.json中多处一个"\\"是正常的，因为JSON的字符串中如果出现"/"需要转义，写成"\\/"。如果我理解错了请告诉我。

第一个问题，你的截图里挡住了文本框所以我不知道你具体是怎么填写的造成的解析错误，我自己按照下图填写，没有问题，请再测试一下。
![image](https://user-images.githubusercontent.com/17154131/43908440-fbad5394-9bc5-11e8-9fbb-5fb98bb32816.png)

**Comment by GitHdu** [comment]
@yfu1900 遇到了相同问题，请问怎么手动修改config.json,找不到文件路径

**Comment by shiningelf** [comment]
我今天第一次用，也发现提示了这个错，其实应该是引号格式不对，例子中的“” 和前面HOST的引号不一样，重新打一下就好了

**Comment by JaguarJack** [comment]
> 我今天第一次用，也发现提示了这个错，其实应该是引号格式不对，例子中的“” 和前面HOST的引号不一样，重新打一下就好了

没有解决啊 试了好多次了 还是没用 不知道什么问题
