### ISSUE TITLE
如何添加域名白名单？

### ISSUE THREAD

**Issue by sxyazi** [Cenmrev/V2RayX#134]
## 问题

当我使用其他 DNS 工具为 `*.dd` 的域名提供解析服务时，遇到问题。（所做的工作是将所有 `*.dd` 的域名解析到 127.0.0.1）。

在浏览器中呈现 HTTP 503 错误。当我关闭或将 V2RayX 设置为 `Manual Mode` 时发现问题解决。

固我怀疑是 V2RayX 与我本地的 DNS 服务发生冲突导致本地服务失效。我在 V2RayX 的设置界面中寻找了类似域名白名单的功能，但是没有找到。

## 尝试

于是我尝试在 `系统偏好设置 -> 网络 -> 高级... -> 代理 -> 忽略这些主机与域的代理设置` 中手动添加 `*.dd` 后发现问题解决。虽然这样解决了问题，但是苦恼的是在 V2RayX 每次设置时会覆盖掉其中的内容。

## 目前的做法

由于使用的 Chrome 浏览器，所以安装了 Proxy SwitchyOmega 插件，使用它里面的域名白名单取消了影响。

## 最后
是否还有其他更加便捷的方法？是否考虑添加白名单功能？感谢你耐心的读完。

**Comment by Cenmrev** [comment]
首先你的DNS工具是放在本地的吗？在 V2RayX 的设置里把 DNS 写成 localhost 行不行？
“V2RayX 每次设置时会覆盖掉其中的内容”确定是 V2RayX 开发过程中不严谨造成的，会在下个版本中修复。
暂时的话可以用 pac 模式过滤掉 *.dd 域名。

**Comment by sxyazi** [comment]
@Cenmrev 是的，我把 dnsmasq 装在了我的本地，但是我并不清楚它的工作流程，我在系统配置的网络配置中将 DNS 设置为 127.0.0.1 并且关闭 V2RayX 可以正常打开 `*.dd` 的域名。而在 V2RayX 中设置的 DNS 却不行。


> 暂时的话可以用 pac 模式过滤掉 *.dd 域名。

这里需要补充的是，PAC 模式不需要添加对 *.dd 的过滤就可打开。无法正常工作的是 V2Ray Rules 与 Global Mode 两个模式，其他均可正常工作。

**Comment by Chandler-Lu** [comment]
代理这个我在使用过程中有时候也会出问题，在个别情况下（无法找到复现规律），unload core以后，系统代理没有被取消掉，导致所有网页被解析到127.0.0.1。但是一直找不到100%复现的方法
至于pac模式不需要添加过滤是因为pac本身分流的形式就不一样

**Comment by tangtangl** [comment]
> 代理这个我在使用过程中有时候也会出问题，在个别情况下（无法找到复现规律），unload core以后，系统代理没有被取消掉，导致所有网页被解析到127.0.0.1。但是一直找不到100%复现的方法
> 至于pac模式不需要添加过滤是因为pac本身分流的形式就不一样

关机或重启前没有unload的话,系统再次启动系统代理取消会失败,在我这里是这样的.作者可以参考一下

**Comment by Cenmrev** [comment]
@sxyazi https://github.com/Cenmrev/V2RayX/releases/tag/v1.5.0-beta2 1.5.0-beta2里加入了路由规则编辑器，应该可以满足白名单的需求了。

**Comment by gzlock** [comment]
@Cenmrev 希望可以写一下路由规则编辑器的教程
