### ISSUE TITLE
导入config.json配置 点击OK，APP闪退？

### ISSUE THREAD

**Issue by Lancenas** [Cenmrev/V2RayX#135]
导入服务端config.json配置 点击OK，APP闪退？

**Comment by Chandler-Lu** [comment]
![2018-08-21 06 44 06](https://user-images.githubusercontent.com/18322610/44370624-9d7a5c80-a50d-11e8-9ce0-54da41071da9.jpg)
注意软件有两个import
- 上方的import是导入并读取config的数据，填写进软件中，这个导入要求config与标准config几乎完全一致，如果你的配置是从网上找的所谓的模板，存在"xxxxx": NULL的填法是必然闪退的。
- 下方的import是不导入参数，直接以该config去load core
因此如果你不是使用官方安装脚本生成的默认config配置，就用下方的吧

**Comment by ITXiaoPang** [comment]
我自己写了脚本用来解析订阅，并通过上方的import导入，结果现在这个功能去掉了，我没法批量导入服务器信息了，希望这个功能加回来，如果担心造成误解，可以尝试改个描述。谢谢作者。

**Comment by Cenmrev** [comment]
@ITXiaoPang https://github.com/Cenmrev/V2RayX/releases/tag/v1.5.0-beta2 已经把从json导入的功能加回来了，支持导入json里outbound/outboundDetour/outbounds这几个key下的标准服务器信息。
