### ISSUE TITLE
HTTP/2的默认设置会使得core无法正确连接

### ISSUE THREAD

**Issue by yuanl** [Cenmrev/V2RayX#139]
我在v2ray-core建了 https://github.com/v2ray/v2ray-core/issues/1242
大意就是在设置HTTP/2 `host`的时候即使是空，v2rayX也会生成一个这样配置
```
      "httpSettings" : {
        "path" : "\/some_radon_path",
        "host" : [
          ""
        ]
      },
```
这时服务器如果没有设置`host`就会认为两边`host`不一样而拒绝连接。

**Comment by Cenmrev** [comment]
谢谢反馈，我会尽快修复
