### ISSUE TITLE
建議：支持以導入 json 文件的方式配置服務

### ISSUE THREAD

**Issue by andy12007** [Cenmrev/V2RayX#14]
可能我比較久沒有更新過，
剛剛升級到新版，打開的時候，之前的配置全部都沒有了。只能重新再設置一次。

建議後期更新能否考慮引入導入 json 文件的方式去配置服務？
至少希望在升級時，不要重置個人配置信息。

感謝！🙏

**Comment by Cenmrev** [comment]
谢谢你的建议！今后的版本我会尽量兼容旧版本的配置信息。
