### ISSUE TITLE
望增加vmess链接导入功能

### ISSUE THREAD

**Issue by ntgeralt** [Cenmrev/V2RayX#141]
今天帮朋友macos装你们的v2rayx，最后填入tls ws客户端配置我感觉操作异常复杂到最后无法启动。又找不到vmess链接导入功能，有些落伍感觉。看能不能改进下 :)

**Comment by Cenmrev** [comment]
行吧...我找个空闲时间研究下

**Comment by Cenmrev** [comment]
已加。

**Comment by ntgeralt** [comment]
thank you verymuch.

**Comment by necodon** [comment]
not va valid link!
从圈里面的分享二维码倒出，不支持该链接
