### ISSUE TITLE
导入config.json，inboud设置为0.0.0.0无效

### ISSUE THREAD

**Issue by ftwater** [Cenmrev/V2RayX#143]
`"inbound": {
        "port": 2333,
        "listen": "0.0.0.0",
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "ip": "192.168.31.64"
        }
    },`
模式选了全局，访问google.com失败
此时查看当前config.json
`"inbound": {
        "port": 2333,
        "listen": "127.0.0.1",
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "ip": "192.168.31.64"
        }
    },`
系统：macos 10.13.6
v2rayX版本：v1.2.2

**Comment by Cenmrev** [comment]
你的意思是你通过`Import customized config files...`导入了自定义的配置文件，然后通过`View current config.json`查看，发现`"0.0.0.0"`被改成了`"127.0.0.1"`? 

V2RayX 不会修改任何导入的自定义配置文件，请检查你是否在菜单里选择了正确的服务器。
