### ISSUE TITLE
1.2.2 奇怪的慢

### ISSUE THREAD

**Issue by mactrash** [Cenmrev/V2RayX#144]
未找出原因

**Comment by Cenmrev** [comment]
core 的原因，或者是你的网络环境变差了。

**Comment by mactrash** [comment]
@Cenmrev 換回上一版，就沒事。希望有人跟進

**Comment by Chandler-Lu** [comment]
你可以自行升级core到目前的最新版，3.38。
1.2.2唯一可能影响实际使用体验的更新只有core update
