### ISSUE TITLE
关于vmess链接解析中tls配置的bug

### ISSUE THREAD

**Issue by Chandler-Lu** [Cenmrev/V2RayX#145]
ConfigWindowController.m的548-550行：
``` objc
if ([sharedServer objectForKey:@"tls"]||[sharedServer[@"tls"] isEqualToString:@"tls"] ) {
         streamSettings[@"security"] = @"tls";
     }
```
鉴于实际配置文件为：
```
// tls关闭
"tls":""

// tls打开
"tls":"tls"
```
所以`sharedServer objectForKey:@"tls"`必然返回True
导致任何链接解析后tls都会打开

**Comment by Cenmrev** [comment]
。。。手滑写错了，应该是 && 而不是 ||

**Comment by Chandler-Lu** [comment]
问你个事- -
用v2ray rule模式实现回国有可能嘛= =
我特么把按钮都写完了才发现好像v2ray的routing策略没法实现geoip:cn走代理其他的全走direct

**Comment by Cenmrev** [comment]
@Chandler-Lu 把 outbound 里写成 Freedom，国内服务器写在 outboundDetour 里，然后路由里面把geoip:cn 导到 outboundDetour 里应该就行了。目前 v2rayx 的 rules 模式只会把代理服务器放在 outbound 里，所以这边需要改一下了。

**Comment by Chandler-Lu** [comment]
是因为只有detour才支持tag么。。QAQ

**Comment by Chandler-Lu** [comment]
get，今早起床研究研究。。
