### ISSUE TITLE
增加对Surge规则的兼容

### ISSUE THREAD

**Issue by hellokitenzihn** [Cenmrev/V2RayX#149]
可能我是小白搜了很久没有发现有比较好的方式能够使用Surge的规则来在Mac上面使用。V2ray很好但是很多不必要的apple icloud线路都走了代理，浪费流量，速度慢。
如果可以增加对surge规则的支持，可以方便很多啊。老大看看？

**Comment by Chandler-Lu** [comment]
以surge做前置代理就行了
或者自己把surge规则改写为pac或者v2ray的routing规则即可

**Comment by hellokitenzihn** [comment]
能否给一个小白教程

**Comment by Chandler-Lu** [comment]
把v2ray有关于routing的部分仔细看一遍吧

**Comment by hellokitenzihn** [comment]
还是蛮复杂的，我看看有没有规则转换器。因为V2ray模式苹果网站全走代理了，官网都走代理，登陆iCloud很麻烦。希望能单独把几个苹果的ip给修正一下。

DOMAIN,books.itunes.apple.com,PROXY//Books
URL-REGEX,*apple.com/cn,DIRECT
USER-AGENT,%E5%9C%B0%E5%9B%BE*,DIRECT//Maps
USER-AGENT,%E8%AE%BE%E7%BD%AE*,DIRECT//Settings
USER-AGENT,*com.apple.mobileme.fmip1,DIRECT
USER-AGENT,*WeatherFoundation*,DIRECT
USER-AGENT,AssistantServices*,DIRECT//Siri
USER-AGENT,MobileAsset*,DIRECT
USER-AGENT,Siri*,DIRECT
USER-AGENT,cloudd*,DIRECT//iCloud
USER-AGENT,com.apple.appstored*,DIRECT//iOS App Store
USER-AGENT,com.apple.geod*,DIRECT
USER-AGENT,com.apple.Maps,DIRECT
USER-AGENT,FindMyFriends*,DIRECT
USER-AGENT,FindMyiPhone*,DIRECT
USER-AGENT,FMDClient*,DIRECT
USER-AGENT,FMFD*,DIRECT
USER-AGENT,fmflocatord*,DIRECT
USER-AGENT,geod*,DIRECT
USER-AGENT,locationd*,DIRECT
USER-AGENT,Maps*,DIRECT
DOMAIN-SUFFIX,aaplimg.com,DIRECT
DOMAIN-SUFFIX,apple.co,DIRECT
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,icloud-content.com,DIRECT
DOMAIN-SUFFIX,itunes.com,DIRECT
DOMAIN-SUFFIX,me.com,DIRECT
DOMAIN-SUFFIX,mzstatic.com,DIRECT//App Store & iTunes Images
DOMAIN-SUFFIX,push-apple.com.akadns.net,DIRECT
IP-CIDR,17.0.0.0/8,DIRECT,no-resolve

**Comment by Chandler-Lu** [comment]
首先，你可以不用v2ray rule模式，改用pac模式，pac并不代理这些域名
其次，如果非要用v2ray rule，可以自己写routing规则，把这些域名写进direct即可

**Comment by hellokitenzihn** [comment]
pac模式下 Mail对Gmail的支持就没有了。
V2ray Rule中我找了很久，找到一个Geosite.dat的文件，但是一修改之后V2rayX.app就无法运行了。能否大神给一个详细一点的指导？
（我尝试了surge但是对我来说是天书啊。。我只会简单代码操作，除了用这个app之外terminal里面怎么设置都无法把v2ray启动。）

**Comment by hellokitenzihn** [comment]
Hello
已经改写了Geosite 方法来自 https://github.com/onplus/v2ray-SiteDAT/releases
可是，V2RayX的rule本身只用GeoIP，还是无法自定义部分网站直链。烦请查看一下


[geosite.dat.zip](https://github.com/Cenmrev/V2RayX/files/2386579/geosite.dat.zip)

**Comment by Chandler-Lu** [comment]
在配置文件的routing下自己加内容，
格式类似于
```
{
          "domain" : [
            "localhost",
          ],
          "type" : "field",
          "outboundTag" : "direct"
        },
```

**Comment by hellokitenzihn** [comment]
打开V2Rayx.app 修改这个config-sample.plist文件么？
我这边配置文件只能在http://127.0.0.1:8070/config.json里面看。找不着啊。不好意思我是热血小白。
反正大家都需要翻墙，能否在下一个更新加入如下特殊规则？
appleid.apple.com已经把谷歌云给封掉了。每次登陆都要切换线路。

1/2直接链接
apple.com
icloud.comaaplimg.comapple.coicloud-content.com
itunes.com
me.commzstatic.compush-apple.com.akadns.net
office.com
office365.com
akamaized.net
microsoft.com

2/2需要翻墙
books.itunes.apple.com

**Comment by Chandler-Lu** [comment]
自行创建一个全新的配置文件，内容参考http://127.0.0.1:8070/config.json，重写routing规则以后导入。
至于特殊规则不可能为特定人群加入的- -上会我提交pr的时候作者应该是有加入custom routing的想法，什么时候能加入我就不知道了

**Comment by hellokitenzihn** [comment]
嗯 我试试
