### ISSUE TITLE
是否有办法批量导入服务器？

### ISSUE THREAD

**Issue by lostcup** [Cenmrev/V2RayX#151]
感谢辛苦劳动，提供了这个客户端，谢谢！

目前功能上似乎暂时不提供订阅功能，那是否有比较容易的办法批量导入服务器配置吗？找来找去也没有发现什么好的方法。

**Comment by Chandler-Lu** [comment]
暂无，目前只支持导入单个vmess://链接

**Comment by jerryli8079** [comment]
如何导入vmess链接呢？

**Comment by Chandler-Lu** [comment]
@jerryli8079 暂时没有发release，您可以使用最新的源码自行编译

**Comment by jerryli8079** [comment]
我还没有学会编译，希望开发组加油发个可以导入vmess和订阅的release，辛苦了

**Comment by zhuohan** [comment]
@jerryli8079 
感谢制作组的劳动，我只是帮你编译一下，如有冒犯，请联系我删除。
链接: https://pan.baidu.com/s/1UpZ9DPmL-zMu3vn_-g-6jg 提取码: 2i79

**Comment by jerryli8079** [comment]
Thanks a lot

**Comment by Cenmrev** [comment]
https://github.com/Cenmrev/V2RayX/releases/tag/v1.5.0-beta2

现在支持从ss和v2ray的json导入服务器的路由规则，（尝试）支持v2rayn的vmess协议和http订阅链接。
