### ISSUE TITLE
关闭v2rayX后就断网

### ISSUE THREAD

**Issue by SuperNG6** [Cenmrev/V2RayX#152]
如题，所有应用都无法联网
重启也无效，必须保持v2rayX开启状态才能联网
版本：最新版。
系统：10.13

**Comment by Cenmrev** [comment]
谢谢反馈，可以提供更多信息吗？“关闭v2rayX”是指 unload v2ray core、还是彻底关掉v2rayX？无法联网状态下，系统设置->网络 是什么样子的？是不是左边的列表被清空了？如果没有被清空，Wi-Fi->高级->代理里面有没有哪一项是被选中的？

**Comment by Chandler-Lu** [comment]
请保证在v2ray关闭时，代理列表中无任何项目被勾选

**Comment by SuperNG6** [comment]
所有选项关闭后正常，感谢

**Comment by Chandler-Lu** [comment]
v2ray关闭后会恢复原始的代理配置。比如你本来某个软件配置了http 127.0.0.1:8001，后开启了v2ray，代理配置被v2ray的配置所覆盖。当v2ray关闭后，配置恢复为http 127.0.0.1:8001。

**Comment by marshal60** [comment]
> 谢谢反馈，可以提供更多信息吗？“关闭v2rayX”是指 unload v2ray core、还是彻底关掉v2rayX？无法联网状态下，系统设置->网络 是什么样子的？是不是左边的列表被清空了？如果没有被清空，Wi-Fi->高级->代理里面有没有哪一项是被选中的？

![2018-09-22 1 12 50](https://user-images.githubusercontent.com/6026982/45895837-de170f80-be04-11e8-99cb-2c5ac5cc4be3.png)
如上图，有三个选项是选中的，手动取消后可以正常上网，不知道 v2rayX 可否做成unload 或者退出后都自动空选这些代理选项？要不然有时候手动空选还是比较麻烦的，多谢了~

**Comment by Chandler-Lu** [comment]
@marshal60 v2rayx本身unload后是恢复原始代理选项，即开启前是什么样，关闭后就是什么样。因此普通用户请保证开启v2rayx前，没有开启任何代理配置。
当然，当v2rayx因为某些原因异常退出的时候，会导致软件关闭而代理配置未恢复。这种情况需要用户手动关闭代理。

**Comment by marshal60** [comment]
> @marshal60 v2rayx本身unload后是恢复原始代理选项，即开启前是什么样，关闭后就是什么样。因此普通用户请保证开启v2rayx前，没有开启任何代理配置。
> 当然，当v2rayx因为某些原因异常退出的时候，会导致软件关闭而代理配置未恢复。这种情况需要用户手动关闭代理。

我系统里面确实装了别的代理软件（surge），但是没有启动，在 10.11 和 10.14 下都试了，都是这个情况。

**Comment by Chandler-Lu** [comment]
@marshal60 保证v2rayx关闭状态下，没有任何其他的代理配置。此时开关v2rayx应该是没有问题的。如果还有问题，请完整描述操作步骤

**Comment by jiuqianyuan** [comment]
我也出现了这个问题，对mac机不了解，现在搞不清楚为什么没有还原

**Comment by Chandler-Lu** [comment]
@jiuqianyuan 目前已知有两个情况不会还原。
1. 因为某种原因，v2rayX崩溃退出。
2. 在v2rayX开启的基础上，有另一个接管系统代理的软件启动，如ss，surge，抓包软件等。

**Comment by jiuqianyuan** [comment]
> @jiuqianyuan 目前已知有两个情况不会还原。
> 
> 1. 因为某种原因，v2rayX崩溃退出。
> 2. 在v2rayX开启的基础上，有另一个接管系统代理的软件启动，如ss，surge，抓包软件等。

之前检测了貌似也没别的代理软件开着，在另一台mac上不是问题，手动测试退出v2rayx还是还原，继续找系统原因ing

**Comment by jiuqianyuan** [comment]
> @jiuqianyuan 目前已知有两个情况不会还原。
> 
> 1. 因为某种原因，v2rayX崩溃退出。
> 2. 在v2rayX开启的基础上，有另一个接管系统代理的软件启动，如ss，surge，抓包软件等。

之前看了貌似也没别的代理软件开着，在另一台mac上没有问题，手动测试退出v2rayx还是不还原，继续找系统原因ing

**Comment by Chandler-Lu** [comment]
@jiuqianyuan 确定一下：开启前，没有任何代理配置；开启后，配置正常。
然后你的问题是，在上述情况下，退出v2rayX，不还原，是吗？
你的v2rayX版本和系统版本是？

**Comment by jiuqianyuan** [comment]
> @jiuqianyuan 确定一下：开启前，没有任何代理配置；开启后，配置正常。
> 然后你的问题是，在上述情况下，退出v2rayX，不还原，是吗？
> 你的v2rayX版本和系统版本是？

找到原因了，关闭软件时必须unload core，如果直接quit退出，就会出现系统代理配置不还原的情况，系统好像是10.几，v2rayX是最新版

**Comment by Chandler-Lu** [comment]
@jiuqianyuan mojave测试确定quit退出也是正常的，没有其他系统测试不了- -

**Comment by puppet1an** [comment]
mojave 突然退出后 就断网了 ，也是醉了。

**Comment by puppet1an** [comment]
情况描述 ， 使用v2ray rules 或者pac 或者全局时候 ，访问github.com 只要切换成 unloaded ，就变成了断网了 。什么都访问不了， 其他软件也断开网络 ， 不管是在unloaded或者 load 状态退出v2rayx ，都变成断网

**Comment by puppet1an** [comment]
按照前面文档提示 ，开启前代理里面勾选选项全部关闭 ，然后在启动 ，unloaded时候正常 ，quiet测试正常 ，系统mojave

**Comment by budongdexiaobai123** [comment]
我也遇到了相同的问题，想了解下。退出v2ray时，网络偏好设置中，没有任何其他的代理配置。可是退出后还是不能上网。显示代理服务错误。我该怎么办

**Comment by colinh543** [comment]
坑爹的设计呀，我也出现了这种情况，一直解决不了

**Comment by jialinxie** [comment]
> 请保证在v2ray关闭时，代理列表中无任何项目被勾选

感谢提醒，果然是代理列表没有清空，哎，搞半天才发现是这个原因

**Comment by 1530734065** [comment]
你好，我的WIN10系统也出现了同样的问题，请问WIN10的代理列表如何清空啊

**Comment by Chandler-Lu** [comment]
> 你好，我的WIN10系统也出现了同样的问题，请问WIN10的代理列表如何清空啊

手边没 win 系统，网上找的，进去关掉

![Xnip2021-07-22_14-30-10](https://user-images.githubusercontent.com/18322610/126598141-3e4af6bf-e04c-41ec-9451-c998a879cd48.jpg)
