### ISSUE TITLE
Pac Mode 使用默认的pac文件无法代理www.google.com

### ISSUE THREAD

**Issue by toutoumu** [Cenmrev/V2RayX#154]
Pac Mode 使用默认的pac文件无法代理www.google.com
pac文件已经重置,使用的版本是1.2.2
其他模式都可以代理访问谷歌

**Comment by Chandler-Lu** [comment]
没出现这个问题。你确认一下用的节点是什么区域的

**Comment by toutoumu** [comment]
vmess://Y2hhY2hhMjAtcG9seTEzMDU6MDgzMWFjMWQtM2YwMy00MDQ3LThmZDEtMjE5ZGRlOGVhZTNlQDUxLjY4LjI5Ljg3OjE2NTk2?network=kcp&kcpHeader=srtp&uplinkCapacity=1&downlinkCapacity=6&aid=0&tls=0&allowInsecure=1&mux=0&muxConcurrency=8&remark=HostDoc-FR  用的这个配置，将里面的内容解码出来一个一个填到软件里




| |
刘斌
邮箱：toutoumu@126.com
|

签名由 网易邮箱大师 定制

在2018年09月29日 21:37，MagicChandler 写道：

没出现这个问题。你确认一下用的节点是什么区域的

**Comment by toutoumu** [comment]
我同事同样的配置可以使用，可能他用的是上一个版本的软件




| |
刘斌
邮箱：toutoumu@126.com
|

签名由 网易邮箱大师 定制

在2018年09月29日 21:40，toutoumu 写道：
vmess://Y2hhY2hhMjAtcG9seTEzMDU6MDgzMWFjMWQtM2YwMy00MDQ3LThmZDEtMjE5ZGRlOGVhZTNlQDUxLjY4LjI5Ljg3OjE2NTk2?network=kcp&kcpHeader=srtp&uplinkCapacity=1&downlinkCapacity=6&aid=0&tls=0&allowInsecure=1&mux=0&muxConcurrency=8&remark=HostDoc-FR  用的这个配置，将里面的内容解码出来一个一个填到软件里




| |
刘斌
邮箱：toutoumu@126.com
|

签名由 网易邮箱大师 定制

在2018年09月29日 21:37，MagicChandler 写道：

没出现这个问题。你确认一下用的节点是什么区域的

**Comment by Chandler-Lu** [comment]
你这个节点太偏门了以至于代理列表里根本没有这个地域的谷歌域名而已。。
要么用`https://www.google.com/ncr`去访问，要么自己把`google.com.co`加进pac列表里
