### ISSUE TITLE
ConfigWindowController的tls设置貌似有点问题

### ISSUE THREAD

**Issue by tonychanczm** [Cenmrev/V2RayX#155]
第551行，原来是这样子的：
    if ([sharedServer objectForKey:@"tls"]||[sharedServer[@"tls"] isEqualToString:@"tls"] ) {
这样就有点问题，如果tls的键所对应的值是空的，那样就会明明没有tls的，添加了之后却会出现tls的情况。私以为，应该改为：
    if ([sharedServer objectForKey:@"tls"]&&[sharedServer[@"tls"] isEqualToString:@"tls"] ) {

**Comment by Chandler-Lu** [comment]
#145

**Comment by Chandler-Lu** [comment]
tls应该还有一个bug就是没有把domain填进tls domain里面
