### ISSUE TITLE
希望可以增加 tcpFastOpen 配置

### ISSUE THREAD

**Issue by gslsoft** [Cenmrev/V2RayX#156]
[https://www.v2ray.com/chapter_02/05_transport.html](https://www.v2ray.com/chapter_02/05_transport.html)

在 "streamSettings"-"sockopt"-"tcpFastOpen" 里面

**Comment by Chandler-Lu** [comment]
这玩意可以给一个示例配置吗？
我刚刚
```
"sockopt": {
                     "mark": "0",
                     "tcpFastOpen": true
 }
```
这样，完全连不上啊- -
