### ISSUE TITLE
建议：加入 ShadowsocksX-NG 中存在的 2 个小功能

### ISSUE THREAD

**Issue by zoakerc** [Cenmrev/V2RayX#16]
- `ShadowsocksX-NG` 中有 `开机启动` 的选项，`V2RayX` 没有找到对应的功能选项框。

- `ShadowsocksX-NG` 中有 `Copy HTTP Proxy Shell Export Line` 的小功能，`V2RayX` 需要自己在命令行敲入 `export` 命令。

**Comment by Cenmrev** [comment]
谢谢你的建议
第一个功能可以通过手动把 V2RayX 添加到启动列表里来完成，方法是打开 macOS 的系统设置->用户与组，登陆项，点击加号选择 V2RayX.app。从精简程序的角度来说这个功能我就没加到程序本体里。
第二个功能我不太理解，V2RayX 本来就只提供 socks5 代理端口，这个 `Copy HTTP Proxy Shell Export Line` 似乎没有意义。当然我可能今后会让 V2RayX 也开一个 http 代理端口。

**Comment by netcookies** [comment]
+1 http proxy

**Comment by solarhell** [comment]
感谢作者。如果可以在命令行使用那真是太好了。

**Comment by Cenmrev** [comment]
Simply added http inboundDetour at port 8001

https://github.com/Cenmrev/V2RayX/commit/4f3792b67631ea76fe7f20d55e6614bc2dcbbdf9

**Comment by solarhell** [comment]
Thanks. 已经可以使用命令行代理了

**Comment by netcookies** [comment]
@Cenmrev `Copy Http Proxy command` 不够完整。

```
export http_proxy="http://127.0.0.1:8001"
export HTTP_PROXY="http://127.0.0.1:8001"
export https_proxy="http://127.0.0.1:8001"
export HTTPS_PROXY="http://127.0.0.1:8001"
```

**Comment by Cenmrev** [comment]
@netcookies 已补全， https://github.com/Cenmrev/V2RayX/commit/c139c3d6c4a540afedfc766d7be626a10b8aa843

**Comment by Jun47** [comment]
1、http代理
2、自动更新pac
3、白名单模式与自动更新白名单
4、开机自启
5、中文支持
6、上架AppStore
