### ISSUE TITLE
Mac Mojave断流问题

### ISSUE THREAD

**Issue by LaurenceSamael** [Cenmrev/V2RayX#161]
发现在Mac Mojave中无论是v2rayx还是shadowsocksX-ng都出现断流问题，看YouTube的时候会出现断流变成无限loading，网页加载的时候会出现图片无法显示，甚至Safari提示网页无法打开。
原本以为是ISP的问题，但是发现相同的Wi-Fi与ISP状态下PC、IOS、Android都很流畅没有断流，唯独Mac会出现断流。在High Sierra也没有断流只有Mojave断，而且是频繁性的发生。
请问怎么解决，麻烦告知一下，谢谢。

**Comment by Chandler-Lu** [comment]
从来没遇到过这个情况

**Comment by LaurenceSamael** [comment]
问题已解决
不知什么原因，我是从High Sierra app商店直接升级到Mojave的，升级完后就是各种断流，网页打不开。不论是Safari还是Chrome都会打不开网页，清了caches都没用。
如果有人和我一样状况可试试cmd+option+p+r+开机，屏幕闪四次后松开开机后就正常了。v2ray可以跑满速不断流了。
