### ISSUE TITLE
请求支持机场订阅功能

### ISSUE THREAD

**Issue by blankhang** [Cenmrev/V2RayX#162]
感谢大佬的辛苦付出~~

**Comment by SSkyang** [comment]
感谢大佬的辛苦付出~~

**Comment by Cenmrev** [comment]
如果只是要导入订阅链接的话，现在已经支持了：https://github.com/Cenmrev/V2RayX/pull/175
如果是要自动从订阅链接更新服务器信息的话，暂时还不支持。

**Comment by ImHUan** [comment]
现在用ClashX 支持订阅了，之前一直是X的老铁，作者加油呀
