### ISSUE TITLE
关于MacBook休眠后唤醒系统，V2RayX的 socks5 代理失效。

### ISSUE THREAD

**Issue by nordwind80** [Cenmrev/V2RayX#165]
OS: macOS 10.13.6
V2rayX Version 1.3.0 (316)

当让系统休眠后再次唤醒，V2RayX的代理会失效。

具体表现为：
1. 系统代理的http, https, socks5 选项都在且正确。
2. 打开safari 发现正常代理，而使用 socks5的软件代理失效。说明http和https正常，socks5失效。
3. 无论各种关闭V2rayX或者系统代理选项都无法恢复（包括重启系统，v2rayX不在启动项）
4. 把V2RayX的socks5端口从1086修改成1090后恢复正常。
5. 今早打开笔记本1090端口再次失效，我跟换端口到1086无效，最后换到1088再次恢复。

我系统内只有V2rayX，没有安装别的代理工具。
如需更多信息请告知我。

谢谢！

**Comment by Chandler-Lu** [comment]
[gfwlist.zip](https://github.com/Cenmrev/V2RayX/files/2501253/gfwlist.zip)
哪个网易的地址被代理了？？？

**Comment by nordwind80** [comment]
感觉咱们这软件挺脆弱的，改个规则safari不能用了，用socks5的还能用。

**Comment by Chandler-Lu** [comment]
我必须要明确和您说一下，v2rayx是v2ray为macOS出的GUI。所谓GUI，只是图形化控制v2ray-core而已。从你反馈的问题来看，这是v2ray-core的bug，并不属于GUI所能管辖的范畴。
此外，mojave下并没有复现出socks5挂掉的问题，也没有复现出v2ray rules模式下网易云被代理的问题

**Comment by Chandler-Lu** [comment]
v2ray rules主要通过ip地址来进行流量分配，原则上所有国内的ip都不可能走代理

**Comment by nordwind80** [comment]
Socks5挂掉是长时间的系统休眠后再唤醒，10分钟休眠都不会产生问题。v2ray rules模式确实会对部分网易的地址做代理，比如网易云音乐的音乐下载播放地址。好像是music.126.com。这问题很久了，不是最近才有，也有很多人说过这问题。

**Comment by nordwind80** [comment]
有意思的是刚好我有网易云音乐的GUI客户端，也有命令行的客户端。当使用v2ray rules规则出问题时表现都一样，都不能播放。

**Comment by Chandler-Lu** [comment]
我休眠一晚上都没有出现过问题- -你可以直接用v2ray-core挂载config文件，然后看看socks5会不会挂掉，如果还会的话，那就是core的问题
网易云我刚刚测试，确实没有走代理。如果你那边有问题的话，可以自己抓个包，找到走代理的域名，然后走direct

**Comment by Chandler-Lu** [comment]
可以提供一下你的config文件么，注意隐去ip和uuid

**Comment by Chandler-Lu** [comment]
什么叫“你有网易云音乐的GUI客户端，也有命令行的客户端”，网易云的命令行客户端是什么东西

**Comment by nordwind80** [comment]
感谢您的回复，起始规则问题都不是事折腾一下就行了。主要是长时间休眠我的代理就失效，我会试试你说的方法，如果有问题我再来向您反映。

再次感谢！

**Comment by dont-see-big-shark** [comment]
我也是同样的问题，就是ss-local冲突了
