### ISSUE TITLE
提交一个删除自定义配置时的逻辑问题

### ISSUE THREAD

**Issue by Chandler-Lu** [Cenmrev/V2RayX#166]
1. import customized config files 导入任意自定义配置
2. server勾选该配置
3. import customized config files 界面删除该配置，并finish
4. 直到步骤3都是成功的，但是在configure面板无法点击OK。
5. 此时如果完全关闭v2rayx，将导致v2rayx下次无法正常启动。

故建议在删除配置并finish的时候，自动切回其他的server，防止上述情况发生

**Comment by Cenmrev** [comment]
我试了几次，未能重现你提到的bug，按道理说，在 `ConfigWindowController.m` 的第227行有一句`[self setSelectedCusServerIndex:[_cusProfiles count] - 1];`已经可以保证`selectedCusServerIndex`总是一个有效的数字，能不能再试一下重现这个bug？谢谢！

**Comment by Chandler-Lu** [comment]
@Cenmrev 给我一个邮箱可以嘛，我把录屏发给你，我更新到1.4.0依然可以复现
