### ISSUE TITLE
开启V2ray Rules后Enpass Chrome插件失效

### ISSUE THREAD

**Issue by cyt7732** [Cenmrev/V2RayX#167]
Enpass Mac版Chrome插件，在开启V2ray Rules后，无法正常与Enpass App联结。刚看到了一个1password的也是不能用的。应该是一个问题。用PAC或者全局就不会与enpass冲突。

**Comment by Cenmrev** [comment]
我不是这个两个软件的用户，所以我也不知到这两个软件用了哪些端口和地址导致了插件失效。V2RayX现在已经支持自行编辑路有规则，有需要的用户自行研究后修改路由规则解决。
