### ISSUE TITLE
v2ray rules能自动识别被墙网址？还是只是另一个类似gfw list的文件

### ISSUE THREAD

**Issue by evindu** [Cenmrev/V2RayX#17]
v2ray rules能自动识别被墙网址？还是只是另一个类似gfw list的文件

**Comment by caobug** [comment]
从gfw list中抽取了部分常用网址出来，其原理一样。

**Comment by to2false** [comment]
@caobug va2ray rules怎么能自己更新呢？pac模式safari好像不起作用，只能用rules，但是不能自定义修改规则诶
