### ISSUE TITLE
新版sockopt问题

### ISSUE THREAD

**Issue by cbdog94** [Cenmrev/V2RayX#171]
新版这个fasttcp没开启时的"sockopt" : {}好像会影响正常使用，感觉是有点不兼容，是不是可以改成在没配置时，就取消这个字段

**Comment by Chandler-Lu** [comment]
提交了- -看看作者最近有没有时间merge吧
当初写的时候本来是关闭的时候把其他参数填进去的。。结果发现并不支持macOS。。然后省事就直接改成了
```
{
}
```
233333，不过好像我这里测试的时候并没有问题emmmmm

**Comment by cbdog94** [comment]
嗯嗯，好像也不太容易复现出来，我之前是看到log里sock argument invalid这样的东西，才怀疑是不是这个字段有问题。然后找半天也确定配置文件在哪？这里可以问一下么，之前好像是包里面的config.json，现在是用cenmrev.v2rayx.v2ray-core.plist这个文件控制么？

**Comment by Chandler-Lu** [comment]
`~/Library/Preferences/cenmrev.V2RayX.plist`这是v2rayx的配置文件，保存着v2rayx里所有的配置。
至于最后被v2ray-core挂载的config.json我也不知道在哪- -那段代码我还没仔细研究过
