### ISSUE TITLE
服务器配置中的地址栏允许多行

### ISSUE THREAD

**Issue by s0fx2** [Cenmrev/V2RayX#172]
服务器配置中的地址栏允许多行，导致生成的json配置文件服务器地址可以是  0.0.0.0 \n0.0.0.0   \n是回车可能是拷贝中带的，导致一直连不上，直到我意识到可能回车了，重新发现地址栏里居然是多行地址

**Comment by Cenmrev** [comment]
感谢反馈，已修复 69ec472b53b8446b922959cf2edd8ecf8f359725
