### ISSUE TITLE
关于客户端的2点建议

### ISSUE THREAD

**Issue by imkratos** [Cenmrev/V2RayX#173]
- 能不能像ss客户端一样，增加GFW更新pac功能

- 可不可以客户端自动更新

希望开发者可以考虑一下，一个小白用户的建议，哈哈哈。

**Comment by aojie654** [comment]
1. pac本来就有的
2. 不是所有人都喜欢自动更新

**Comment by Chandler-Lu** [comment]
1. pac每半年也就新增200多条，而且大部分都是一些没有什么软用的地址，如果平常使用的时候发现某个域名无法正常访问，手动加进pac就OK了。
2. 每次客户端更新必然伴随着core updated，但是原则上本地的core版本和服务端core版本匹配是最好的，本地core版本再高，服务端并不支持这个特性一样没用。
