### ISSUE TITLE
vmess 链接无法导入

### ISSUE THREAD

**Issue by diamond-duke** [Cenmrev/V2RayX#174]
任何一个链接导入总是显示 `Unknown format or Unknown link version!`。

我稍微研究了一下代码，在 `ConfigWindowController.m` 中的第 `534` 行中，`sharedServer[@"v"]` 好像其实是一个 `NSNumber` 而不是 `NSString`，导致了 `sharedServer[@"v"] isNotEqualTo:@"2"]` 永远返回否？

我不太懂 objective-C，所以也可能是其他问题。

**Comment by Chandler-Lu** [comment]
目前只支持v2rayN for win生成的vmess链接。目前不同客户端使用不同的分享链接版本，我所知道的就有三种（win/Android，iOS-Shadowrocket，iOS-Quantumult），而且实际上好像还不止这几种
