### ISSUE TITLE
客户端1.3无法编辑websocket的headers内容，键入会报错，但复制粘贴可以，作者有空可以看下

### ISSUE THREAD

**Issue by salmonkiller** [Cenmrev/V2RayX#176]
客户端直接修改websocket的headers时，会报错说无法解析，键入大于一次就会报错，但直接复制粘贴可以，作者有空可以验证一下。

**Comment by PatrickGuo** [comment]
右键substitution取消smart quote就行了…

**Comment by imkratos** [comment]
恩我也发现这个问题了，主要是把 "" 会自动替换成中文的。所以造成json不能解析
