### ISSUE TITLE
我的v2rayX后台总是高速下载，不知道怎么回事？

### ISSUE THREAD

**Issue by 839891627** [Cenmrev/V2RayX#177]
![image](https://user-images.githubusercontent.com/10300651/48547272-2e8e8300-e905-11e8-932e-25d6fabaf5c9.png)

**Comment by 839891627** [comment]
小白没明白，所以很慌。。 忘懂得帮解答下~

**Comment by Chandler-Lu** [comment]
从域名来看疑似chrome数据同步或更新

**Comment by 839891627** [comment]
> 从域名来看疑似chrome数据同步或更新，具体要看无操作时候抓包结果，你这个log啥都有，无法确定来源

好的。我再留意下~

**Comment by Chandler-Lu** [comment]
另外当v2ray接管系统代理之后，原则上所有的上下行流量应该都会算到v2ray头上。
istats我没用过，不清楚是怎么监测流量的。
不过这个基本上可以放心，只要不是24小时每时每刻都在跑流量，一般没什么问题

**Comment by imkratos** [comment]
我也遇到这个问题了，选择v2ray 规则代理的情况下，感觉有些流量也会走v2ray，但不知道在哪里确定，是不是说v2ray会接手所有的流量，但走不走代理它内核再去判断。istat来看，就是走v2ray的了。
![image](https://user-images.githubusercontent.com/3302461/48614567-7f67af80-e9c9-11e8-9574-a6c5bc3419d3.png)

**Comment by Chandler-Lu** [comment]
> 我也遇到这个问题了，选择v2ray 规则代理的情况下，感觉有些流量也会走v2ray，但不知道在哪里确定，是不是说v2ray会接手所有的流量，但走不走代理它内核再去判断。istat来看，就是走v2ray的了。
> ![image](https://user-images.githubusercontent.com/3302461/48614567-7f67af80-e9c9-11e8-9574-a6c5bc3419d3.png)

在pac模式下，只有代理流量走v2ray，在其他模式（除手动）下，所有流量走v2ray，然后分流

**Comment by imkratos** [comment]
> > 我也遇到这个问题了，选择v2ray 规则代理的情况下，感觉有些流量也会走v2ray，但不知道在哪里确定，是不是说v2ray会接手所有的流量，但走不走代理它内核再去判断。istat来看，就是走v2ray的了。
> > ![image](https://user-images.githubusercontent.com/3302461/48614567-7f67af80-e9c9-11e8-9574-a6c5bc3419d3.png)
> 
> 在pac模式下，只有代理流量走v2ray，在其他模式（除手动）下，所有流量走v2ray，然后分流

恩，那我能知道，在其他模式(除手动)下，怎么分流的吗，有没有日志或者规则可以查看。
还有个问题，pac如何手动更新，我想把GFW手动导入进来，但看到还要程序转一下，因为是加密的，如果有方法，多谢帮忙。

非常感谢您的回复。

**Comment by Chandler-Lu** [comment]
@imkratos #127 这个问题我写过，在v2ray rules模式下，又v2ray内置的规则分配。pac模式下，由pac文件分配。
自行扩充pac文件建议使用https://github.com/petronny/gfwlist2pac这个项目的列表，原生gfwlist做base64解码后的格式并不被支持
