### ISSUE TITLE
Global 疑问

### ISSUE THREAD

**Issue by CrazyMouse** [Cenmrev/V2RayX#178]
有个问题一直没搞明白就是，我开启Global模式的情况下，我的理解，所有的流量都会走代理出去的了，那么我访问公司内网WEB（网段172.28.*.*）的时候，应该访问失败才对，用ShadowsocksX-NG的时候和我理解的一致，内网的无法访问，可是用v2RayX的时候居然可以正常访问，请问这是什么原因呢？

**Comment by Chandler-Lu** [comment]
全局模式下，有一个过滤规则是始终生效的，叫做`geoip:private`，包括所有的私有地址。其中你们的内网`172.28.0.0/`属于B类私有地址`172.16.0.0 – 172.31.255.255`，故依然在不走代理的列表之类。
使用该过滤是为了防止在全局模式下，用户无法正常访问内网，无法正常访问路由等问题

**Comment by CrazyMouse** [comment]
@Chandler-Lu 感谢感谢 总算明白原因了 也就是说 v2RayX本身是收到了内网域名的代理请求的 只不过判定发现是属于内网网段就不走代理模式了 而ShadowsocksX-ng没加判断 是这个意思吗？不知道我理解的对不对 还望赐教 谢谢

**Comment by Chandler-Lu** [comment]
对的，v2ray自带的路由控制文件除正常的分流之外，还有几个特殊的分流情况，其中就包括私有地址的分流。ssr并没有这个特性

**Comment by CrazyMouse** [comment]
@Chandler-Lu  完全明白了，非常感谢您的解惑
