### ISSUE TITLE
启动状态下切换到manual模式系统代理没有取消

### ISSUE THREAD

**Issue by KyonLi** [Cenmrev/V2RayX#18]
manual mode -> start -> global mode -> manual mode -> 系统代理仍然为socks

**Comment by Cenmrev** [comment]
已尝试修复https://github.com/Cenmrev/V2RayX/commit/177c82d81e2d84f85a07ee9faf9b05489a51f045

**Comment by KyonLi** [comment]
@Cenmrev 问题依旧

**Comment by KyonLi** [comment]
@Cenmrev ShadowsocksX那样的逻辑会不会清晰一些呢：程序运行即监听本地端口，菜单中的Start/Stop只是控制是否设置系统代理。Manual mode = Global mode + Stop.
