### ISSUE TITLE
关于v2rayN.exe生成的vmess导入v2rayx后，无法使用问题

### ISSUE THREAD

**Issue by ntgeralt** [Cenmrev/V2RayX#184]
你好，我建议导入剪切板的vmess功能放出来更明显地方

另外我反应个问题：
我在v2rayN.exe选择个tls ws 的服务端vmess，在v2rayx导入后。发现无法使用。

然后我在transport setting里发现有些信息多出来。如tls那栏的server.cc，在，v2rayN里没有，在我服务端也没有。

之后删掉就能用了；

**Comment by Chandler-Lu** [comment]
修复这个问题的代码已经合并了只是没有发release而已
