### ISSUE TITLE
导入vmess二维码链接后提示：Unknown format or Unknown link version!

### ISSUE THREAD

**Issue by miaojun888** [Cenmrev/V2RayX#185]
我买的代理是v2ray类型的，他们有样式订阅，在windows下用v2rayN，可以一次性把所有 服务器节点都导入，但在mac上用这个v2ayX,没有找到有这个样式订阅的功能，而且导入二维码链接也报错，没办法导入，请问是什么问题呢？

**Comment by cnpcshangbo** [comment]
我也遇到了同样的问题。该问题已经解决了吗？

**Comment by Chandler-Lu** [comment]
您好，您给我的邮件已经收到，检查了一下您的分享链接，发现原因如下：
> 以下配置已删除敏感信息

根据[vmess分享链接标准](https://github.com/2dust/v2rayN/wiki/分享链接格式说明(ver-2))，正确数据应该如下：
```
{
    "v": "2",
    "add": "example.com",
    "ps": "测试用",
    "port": "10000",
    "id": "xx-xx-xx-xx",
    "aid": "2",
    "net": "ws",
    "type": "none",
    "host": "example-1.com",
    "path": "/",
    "tls": "tls"
}
```
而你所购买的v2ray分享链接并不符合这一标准：
```
{
    "v": 2, // 引号丢失
    "add": "example.com",
    "ps": "测试用",
    "port": "10000",
    "id": "xx-xx-xx-xx",
    "aid": "2",
    "net": "ws",
    "type": "none",
    "host": "example-1.com",
    "path": "/",
    "tls": "tls"
}
```
v2rayX根据会根据上述分享标准对分享链接进行校验，故给出错误提示
https://github.com/Cenmrev/V2RayX/blob/932699524384ed3d89ab9f9f86e9ce7486f9c0ce/V2RayX/ConfigWindowController.m#L534-L537

是否需要修复这个还是问问owner吧，@Cenmerv

**Comment by yanue** [comment]
抱歉打广告来了, 欢迎使用:  https://github.com/yanue/v2rayu,支持ss,vmess导入,手动编辑,分享
