### ISSUE TITLE
MAC无法打不开V2RAYX

### ISSUE THREAD

**Issue by lyonye** [Cenmrev/V2RayX#188]
下载最新版本V2RAYX，在MAC OS电脑10.14.1打开出现下面提示：
V2RayX needs to install a small tool to /Library/Application Support/V2RayX/ with administrator privileges to set system proxy quickly.

输入密码后，为何不会打开程序呢？

**Comment by Cenmrev** [comment]
可以具体一点吗？输入你的macOS管理员密码以后操作系统是什么反应？“打不开”是指输完密码后什么反应都没发生？V2RayX启动时不会显示窗口，检查一下操作系统的右上角有没有出现一个V字的图标？

**Comment by lyonye** [comment]
谢谢回复。应该是版本问题，后来我换成就的版本就可以看到右上角有一个V图标。谢谢。
