### ISSUE TITLE
config.json is not a valid v2ray config file

### ISSUE THREAD

**Issue by wangshaonan** [Cenmrev/V2RayX#193]
您好，

买了新的mac电脑，把之前mac的V2RayX软件和config.json移到新电脑上，config.json怎么也导不进去，请问这可能是什么问题？路径是没问题的，都是/Users/name/Download/config.json

谢谢

**Comment by Chandler-Lu** [comment]
检查一下config有没有问题吧

**Comment by wangshaonan** [comment]
同样的config，原来的mac上可以导入，新的mac电脑就不行

**Comment by Chandler-Lu** [comment]
建议把config放上来再说

**Comment by wangshaonan** [comment]
已经解决了。config的内容应该没什么问题，因为之前的mac是可以导入的，新的mac确实导入不了。解决方案是从网上找了一个config.json，可以导入到新电脑，然后把参数改了，就可以了。
