### ISSUE TITLE
v2ray 1.4 版本 unload core 或者关闭软件就无法上网

### ISSUE THREAD

**Issue by shenyunhuan** [Cenmrev/V2RayX#194]
v2ray 1.4 版本 unload core 或者关闭软件就无法上网
macos 10.14

**Comment by shenyunhuan** [comment]
然后我在网络 高级 代理 里把所有的都取消勾选才能上网
建议加两个逻辑，当unload core 或者关闭软件时把代理里所有的都取消勾选，
而且加监听事件，当软件没有开启开机自启时，关机软件生命周期结束时，把代理里所有的都取消勾选

**Comment by Cenmrev** [comment]
这个问题没有这么简单：

>当unload core 或者关闭软件时把代理里所有的都取消勾选，

如果软件从启动就选择了手动模式，软件就不应当碰系统的代理。有的用户只想用v2rayx当作core的加载器，如果v2rayx在退出时把所有代理都关掉，这些用户就不开心了。

> 加个监听事件，当软件没有开启开机自启时，软件的生命周期结束时，把代理里所有的都取消勾选

同理，选择手动模式的用户只是打开了下就发现系统代理全都被关掉了，肯定不开心了。

V2RayX 现在的采取的策略是，当V2RayX开始接管系统的代理时（开启非手动模式），备份系统的代理情况。当V2RayX不再接管系统的代理时（彻底退出，或者选择手动模式），就把之前的代理恢复。

这个策略会在一种情况下失败，就是 V2RayX 没有正常退出导致系统的代理没有被正常恢复，那么在下次启动时，软件就会备份错误的系统代理信息。
