### ISSUE TITLE
1.4版本transport settings奇葩bug

### ISSUE THREAD

**Issue by c0rpse** [Cenmrev/V2RayX#195]
macOS下手工配置WebSocket的headers内容，为啥英文双引号一直自动给我切换成中文双引号？？？
这样的话软件会一直提示解析自定义websocket headers错误！

**Comment by c0rpse** [comment]
新发现：如果把配置粘贴进去，不会出现这种问题。但是如果手动添加，会出现这个问题。

**Comment by tangtangl** [comment]
> 新发现：如果把配置粘贴进去，不会出现这种问题。但是如果手动添加，会出现这个问题。

macos系统设置,键盘,文本选项卡下面使用智能引号破折号前面的√去掉试试.

**Comment by Cenmrev** [comment]
https://github.com/Cenmrev/V2RayX/issues/176，发帖之前先搜索
这是macos自己自作聪明的问题，跟v2rayx没关系。下个版本会强制关闭智能引号。
