### ISSUE TITLE
1.5不支持v2ray rules了吗？

### ISSUE THREAD

**Issue by LaurenceSamael** [Cenmrev/V2RayX#198]
刚下了beta2版发现没了v2ray rules，感觉这个比pac rules好用。

**Comment by Cenmrev** [comment]
支持。1.5里面，全局模式+routing里面选择bypasscn_apple就是以前的v2ray rules，并且可以自行编辑和增减路由规则。

**Comment by LaurenceSamael** [comment]
谢谢大佬回复
