### ISSUE TITLE
Manual mode 内置规则问题

### ISSUE THREAD

**Issue by KyonLi** [Cenmrev/V2RayX#20]
看到的不正常的现象: 
Manual mode下SSH客户端通过代理连接非标准端口VPS，结果没有走代理，是直连的。

期待看到的正确表现: 
Manual mode只要调用就走代理，不预置内部规则。

**Comment by Cenmrev** [comment]
Please try https://github.com/Cenmrev/V2RayX/releases/tag/v0.9 and report bugs.
Thank you!
