### ISSUE TITLE
进入 Advanced 界面后点击 Cancel 和 Finish 窗口没有关闭，这时点击界面的 "+" " -" 或者 Help Cancel Finish 其中一个按钮程序会秒退

### ISSUE THREAD

**Issue by fzred** [Cenmrev/V2RayX#202]
Version 1.5.0 (1236)
操作系统： macOS 10.12.3

**Comment by Cenmrev** [comment]
@fzred 你好，我猜测可能和你用的操作系统是10.12.3有关系。如果你愿意，所以请在命令行（终端.app）里运行`/Applications/V2RayX.app/Contents/MacOS/V2RayX`，重复上述操作直至软件崩溃，把终端里的输出贴上来。注意这一步把所有内容贴上来的时候，请把内容包括在两行```之间，如果有涉及个人隐私的内容请隐去。例子:
<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>```
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```
</code></pre></div></div>

谢谢合作。

**Comment by fzred** [comment]
@Cenmrev  我重复运行了大概 40 次，软件并不会崩溃
![jietu20181230-202906](https://user-images.githubusercontent.com/7991717/50547261-c3f59480-0c71-11e9-92bd-f688ed83a070.jpg)
![jietu20181230-202911](https://user-images.githubusercontent.com/7991717/50547263-c5bf5800-0c71-11e9-8f7d-c6136e1f09e2.jpg)

**Comment by Chandler-Lu** [comment]
如有可能删除以下所有文件（会丢失所有用户配置），然后下载全新的v2rayX并配置
```
/Applications/V2RayX.app
/Users/用户名/Library/Preferences/cenmrev.V2RayX.plist
/Users/用户名/Library/Application Support/V2RayX
/Library/Application Support/V2RayX
```

**Comment by fzred** [comment]
@Chandler-Lu 已经删除重新下载安装，还是一样的问题
![jietu20181230-203854](https://user-images.githubusercontent.com/7991717/50547376-a7f2f280-0c73-11e9-815b-6d7ade0e42d0.jpg)

**Comment by Cenmrev** [comment]
> @Cenmrev 我重复运行了大概 40 次，软件并不会崩溃

@fzred 抱歉，怪我没有表述清楚。我说“重复上述操作直至软件崩溃”是指：运行`/Applications/V2RayX.app/Contents/MacOS/V2RayX`之后，在打开的V2RayX软件中，重复你的操作（打开advanced窗口，点击cancel，无法退出，四五秒后闪退），不是指把`/Applications/V2RayX.app/Contents/MacOS/V2RayX`这条命令重复执行四五十遍。

所以完整表述一遍我想请你做的测试：在菜单栏上所有的V字图标里选择quit，保证所有的V2RayX已经退出。然后运行`/Applications/V2RayX.app/Contents/MacOS/V2RayX`，这时候菜单栏上会出现V2RayX，然后进行你的操作（打开advanced窗口，点击cancel，无法退出，四五秒后闪退），把终端里的输出反馈给我，谢谢合作。

**Comment by fzred** [comment]
我重新试了下，跟标题描述的情况有点不一样，可能是之前没看仔细，现在情况是：
点击 Cancel 和 Finish 窗口没有关闭，这时窗口的 Tab(Outouds,Subscription,Rules....) 可以正常点击切换，但是点击界面的 "+" " -" 或者 Help Cancel Finish 其中一个按钮程序会秒退。
```
╰─ /Applications/V2RayX.app/Contents/MacOS/V2RayX ; exit;
2018-12-31 00:36:23.187 V2RayX[13087:930561] pac file is switched to pac.js
[INFO] GCDWebServer started on port 8070 and reachable at http://192.168.199.133:8070/
2018-12-31 00:36:23.192 V2RayX[13087:930561] 8, -1
2018-12-31 00:36:23.212 V2RayX[13087:930561] use core: /Applications/V2RayX.app/Contents/Resources/v2ray
2018-12-31 00:36:23.213 V2RayX[13087:930561] system proxy state:on,0
2018-12-31 00:36:23.263 V2RayX[13087:930561] updatePacMenuList
2018-12-31 00:36:23.366 V2RayX[13087:930564] proxy set to off
2018-12-31 00:36:23.442 V2RayX[13087:930564] proxy set to auto
[1]    13087 segmentation fault  /Applications/V2RayX.app/Contents/MacOS/V2RayX

[进程已完成]
```

**Comment by Cenmrev** [comment]
@fzred 希望你能用1.5.1beta版本重复一遍运行/Applications/V2RayX.app/Contents/MacOS/V2RayX的测试以帮助我更好地定位问题所在。

**Comment by Cenmrev** [comment]
@iGGrk 你的操作系统版本是什么？
