### ISSUE TITLE
1.5.0的tls设置不能设置servername

### ISSUE THREAD

**Issue by Abderrian** [Cenmrev/V2RayX#203]
1.5.0的tls设置不能设置servername
标题已经把要说的都说完了。 ⁄(⁄ ⁄ ⁄ω⁄ ⁄ ⁄)⁄

**Comment by Chandler-Lu** [comment]
删掉了这个设置，我暂时没有想到需要在server ip和tls domain中填写不同参数的情况

**Comment by Abderrian** [comment]
如果网站没有用cdn， server address填ip地址，tls servername填域名，就不用每次都进行dns查询了。

**Comment by smoothdvd** [comment]
@Abderrian @Chandler-Lu #201

**Comment by Chandler-Lu** [comment]
@smoothdvd 你这个肯定是啊，都开了tls怎么可能还用ip，当然要用域名啊

**Comment by smoothdvd** [comment]
@Chandler-Lu 1.3的逻辑不是这样的

**Comment by Chandler-Lu** [comment]
@smoothdvd #164 我删掉的，防止在解析vmess url的时候，tls domain 被填入错误的参数

**Comment by smoothdvd** [comment]
@Chandler-Lu 明白了，不麻烦的话最好在README或者changelog里说明一下。

**Comment by Abderrian** [comment]
@Chandler-Lu server address不填ip地址，而填域名的话，我每次访问v2ray代理不是都要先在客户端本地进行一次dns查询，把域名解析成ip地址吗？
server address直接填ip地址，tls servername填域名，不就不用先在客户端本地进行一次dns查询了。

**Comment by Chandler-Lu** [comment]
@Abderrian 我知道你的意思，只是好像没有什么本质性的影响

**Comment by Chandler-Lu** [comment]
老版本正常新版本异常，你给出config和log啊。。说了半天都是废话，等于没问

**Comment by jackwangshanghai** [comment]
Version 1.5.0 (1236) 中 TLS name 被强制设为server.cc。导致 TLS验证时候出现TLS域名错误。能否考虑将默认的TLS Name设置为和服务器地址一样。（4.9的 Core QUIC配置下 TLS Name留空貌似也不行）

**Comment by Chandler-Lu** [comment]
@jackwangshanghai tls打开时tls domain会被设定为服务器地址，tls关闭时tls domain参数无意义，怎么会出现错误

**Comment by Cenmrev** [comment]
@jackwangshanghai 你好，谢谢反馈，这里确实有个bug。

@Chandler-Lu 这里有个bug，tls server name 只有打开 transport settings 并保存时才会被设定。有一种情况是，用户的address写的还是server.cc，先打开  transport settings 开启tls，保存，这时候 tls domain 也会被设置成 server.cc，然后用户发现server.cc错了，改成他的地址。但这个时候 tls domain 还没被改过来。然后就出现似乎 tls domain 被锁定成 server.cc 的假象了。最简单的解决办法是找个时间把 tls domain 的文本框加回去。

**Comment by Chandler-Lu** [comment]
@Cenmrev 我昨天下午准备加文本框的时候也发现这个问题了，但是我确实没明白这个bug是什么情况，按理说tls domain会被直接初始化为`configWindowController.selectedProfile.address`

**Comment by Chandler-Lu** [comment]
@Cenmrev 明白了，但是这就有一个问题，当用户通过vmess url导入配置了tls的服务器时，必须手动打开TransportSettings来设定tls domain，这个问题即使加上文本框也没有办法解决呐。

**Comment by Chandler-Lu** [comment]
@Cenmrev 另外还有个小问题我就不发issue了，import那里的表述我觉得可能有点不太好。
本身v2rayX是一个以vmess为主的东西，而把`ss://`叫做`standard share link`会让人误会，而且用miscellaneous好像确实让人不太好理解。
如有可能的话，改成
```
import from v2rayN links
import from SS links
import from other mixing links
```
可能会好些？

**Comment by Cenmrev** [comment]
> @Cenmrev 明白了，但是这就有一个问题，当用户通过vmess url导入配置了tls的服务器时，必须手动打开TransportSettings来设定tls domain，这个问题即使加上文本框也没有办法解决呐。

比如v2rayn格式的分享链接，这个可以通过导入的时候，就把tls domain设置成和`add`一样来解决。但是如果原来`add`就不是域名，或者用户是完全自己手动配置tls的，那只能让用户手动打开TransportSettings来设定tls domain了。

> @Cenmrev 另外还有个小问题我就不发issue了，import那里的表述我觉得可能有点不太好。
> 本身v2rayX是一个以vmess为主的东西，把`ss://`叫做`standard share link`会让人误会，而且用`miscellaneous`这种GRE词汇确实有点不太好理解。
> 如有可能的话，改成
> 
> ```
> import from v2rayN links
> import from SS links
> import from other mixing links
> ```
> 
> 可能会好些？

用`standard share link`的本意是想说这里可以导入各种官方的标准链接，包括即将推出的[官方vmess链接](https://github.com/v2ray/v2ray-core/issues/1487)。其他链接放在`mixing`里面。优先支持官方链接，其他格式链接出了兼容性问题不一定跟进，比如之前v2rayn协议里`2`和`"2"`那个问题。
