### ISSUE TITLE
关于Routing Rule的疑惑

### ISSUE THREAD

**Issue by mela93** [Cenmrev/V2RayX#204]
0) 如果你没有遇到任何错误和不正常，请在此处回答你想发表的内容：
```
1. 请问是否可以添加从GWF list更新pac的功能？
[看到#15](https://github.com/Cenmrev/V2RayX/issues/15) 里建议使用v2ray rules 
新版已经没有v2ray rules 请问该怎么解决？
2. 新版1.5.0，不管我选择什么模式，但是Routing Rule没选对就无法使用。
假设我选pac模式，但是Routing Rule选择all to direct就无法访问。
请问是否功能冲突了？
感觉Routing Rule是最高层级的，那么选pac还是全局模式好像就无意义了
如果是我使用方法和理解有错误请谅解。
```

1) 你正在使用哪个版本的 V2RayX，你的 macOS 系统版本？
```
V2RayX V 1.5.0 (1236)
MacOS 10.14.2
```

**Comment by Chandler-Lu** [comment]
你可以这么理解。
在 pac 模式下，
![example](https://user-images.githubusercontent.com/18322610/50625241-b25a0880-0f61-11e9-9f19-a6084e313afe.png)

故：
1. pac + all_to_main 相当于原有pac模式
2. global + bypasscn 相当于原有v2ray rules模式

**Comment by mela93** [comment]
Ok, cool. 了解了！
讲解和图示很清晰，多谢大佬解答。
