### ISSUE TITLE
提问：如何在两个服务器中智能选择？

### ISSUE THREAD

**Issue by hellokitenzihn** [Cenmrev/V2RayX#208]
请回答下列问题。不按模板发的 issue 将直接被关闭。

0) 如果你没有遇到任何错误和不正常，请在此处回答你想发表的内容：

**您好，我现在有两个服务器，一个谷歌云台湾（速度非常好），一个英国的（需要看bbc）想问一下有什么简单的方法可以自动设置当访问bbc.co.uk的时候走英国服务器，其他时候走谷歌服务器？**

1) 你正在使用哪个版本的 V2RayX，你的 macOS 系统版本？
1.5正式版

**Comment by Chandler-Lu** [comment]
可以自己写config，GUI没有这个功能：https://www.v2ray.com/chapter_02/03_routing.html

**Comment by Cenmrev** [comment]
你好，没有一键操作，但你可以编辑路由规则来完成，详细的细节和原理你可以参考楼上的链接，强烈建议你先读一下。我只说一下GUI里怎么操作。

既然你说
> 当访问bbc.co.uk的时候走英国服务器，其他时候走谷歌服务器

我假设你用了pac模式来首先区分国内外流量，只把出国流量发给v2ray。那么你首先要给你的两台服务器都加上tag，假设分别叫做`twgcp`和`ukbbc`，然后在config->advanced->rules里面新建一套规则，规则名随意（假设叫`tw_and_uk`），strategy选择asis，点击+好加一条规则，钩上domain，填入 
```
domain:bbc.co.uk
---
```
route to 选择 ukbbc
然后在第二条规则(final)里，route to 选择 twgcp。保存。
<img width="366" alt="image" src="https://user-images.githubusercontent.com/17154131/50857132-b7042f80-135a-11e9-94bf-782f69b1fdf5.png">

最后在主菜单上routing rule，选择`tw_and_uk`就行了。

**Comment by hellokitenzihn** [comment]
> 你好，没有一键操作，但你可以编辑路由规则来完成，详细的细节和原理你可以参考楼上的链接，强烈建议你先读一下。我只说一下GUI里怎么操作。
> 
> 既然你说
> 
> > 当访问bbc.co.uk的时候走英国服务器，其他时候走谷歌服务器
> 
> 我假设你用了pac模式来首先区分国内外流量，只把出国流量发给v2ray。那么你首先要给你的两台服务器都加上tag，假设分别叫做`twgcp`和`ukbbc`，然后在config->advanced->rules里面新建一套规则，规则名随意（假设叫`tw_and_uk`），strategy选择asis，点击+好加一条规则，钩上domain，填入
> 
> ```
> domain:bbc.co.uk
> ---
> ```
> route to 选择 ukbbc
> 然后在第二条规则(final)里，route to 选择 twgcp。保存。
> <img alt="image" width="366" src="https://user-images.githubusercontent.com/17154131/50857132-b7042f80-135a-11e9-94bf-782f69b1fdf5.png">
> 
> 最后在主菜单上routing rule，选择`tw_and_uk`就行了。

此方案已解决问题。
