### ISSUE TITLE
v1.5.0 UI中配置完后，json无变化。

### ISSUE THREAD

**Issue by nbjyk** [Cenmrev/V2RayX#209]
请回答下列问题。不按模板发的 issue 将直接被关闭。

1) V2RayX版本1.5.0，系统版本 macOS 10.14.2

2) 不正常行为：在Configure中添加了服务器信息，保存并选择。再View current config.json，现实的配置无变化。也无法使用。似乎UI中编辑的信息，并不会改变config.json的内容。内容如下：

```json
{
  "dns" : {
    "servers" : [
      "localhost"
    ]
  },
  "inbounds" : [
    {
      "listen" : "127.0.0.1",
      "port" : 1081,
      "protocol" : "socks",
      "tag" : "socksinbound",
      "settings" : {
        "auth" : "noauth",
        "udp" : false,
        "ip" : "127.0.0.1"
      }
    },
    {
      "listen" : "127.0.0.1",
      "port" : 8001,
      "protocol" : "http",
      "tag" : "httpinbound",
      "settings" : {
        "timeout" : 0
      }
    }
  ],
  "outbounds" : [
    {
      "tag" : "direct",
      "protocol" : "freedom",
      "settings" : {

      }
    }
  ],
  "routing" : {
    "name" : "all_to_direct",
    "domainStrategy" : "AsIs",
    "rules" : [
      {
        "type" : "field",
        "outboundTag" : "direct",
        "port" : "0-65535"
      }
    ]
  },
  "log" : {
    "error" : "\/var\/folders\/bd\/dn7z3q0x73n0w7fwlycw2w7h0000gn\/T\/cenmrev.v2rayx.log\/error.log",
    "loglevel" : "info",
    "access" : "\/var\/folders\/bd\/dn7z3q0x73n0w7fwlycw2w7h0000gn\/T\/cenmrev.v2rayx.log\/access.log"
  }
}
```

**Comment by Chandler-Lu** [comment]
什么叫添加了服务器信息？
`view current config.json`显示的是当前运行的配置，你要在`server`中切换到你配置的服务器才能用啊

**Comment by nbjyk** [comment]
> 什么叫添加了服务器信息？
> `view current config.json`显示的是当前运行的配置，你要在`server`中切换到你配置的服务器才能用啊

嗯，server选项已经切换到我先前添加的那个server了，但view current config.json，显示的信息不是我选择的那个server配置，而是如上所示。特别是outbound那块，正常的话应该显示我的服务器配置吧。

**Comment by Chandler-Lu** [comment]
如有可能的话提供一下Server和Configure的截图？

**Comment by lcl2539** [comment]
我出现了同样的问题，环境相同，版本相同，但是在我另一台Mac上是好的

**Comment by nbjyk** [comment]
> 如有可能的话提供一下Server和Configure的截图？

暂时已经卸载了，但v1.3.0的时候用的没问题，应该不是我不熟悉导致的。明后天安装的时候，再截图吧。

**Comment by Cenmrev** [comment]
这是因为路由规则选择了`all_to_direct`，所以增删配置不会改变配置文件。我把默认路由规则改成`all_to_main`吧...

**Comment by Chandler-Lu** [comment]
@Cenmrev 噗。。这是feature还是bug23333

**Comment by Cenmrev** [comment]
@Chandler-Lu 照你的图扩展了下: [wiki](https://github.com/Cenmrev/V2RayX/wiki/V2RayX-Logic-Explained-%E9%80%BB%E8%BE%91%E8%AF%B4%E6%98%8E)
