### ISSUE TITLE
关于配置菜单的优化

### ISSUE THREAD

**Issue by cs50Mu** [Cenmrev/V2RayX#21]
建议在配置菜单中，增加对用户输入的trim处理（去掉首尾的空格等）

刚刚折腾了半天，才发现是Address填的时候后面多了一个空格。。。 #

**Comment by Cenmrev** [comment]
谢谢建议，已增加[相关代码](https://github.com/Cenmrev/V2RayX/commit/aea8109520fc10fe882d103ab338fe0b534c39f1)，下个版本 release 时生效。
