### ISSUE TITLE
How to completely remove V2RayX?

### ISSUE THREAD

**Issue by aeroxy** [Cenmrev/V2RayX#219]
Is there a command built in or an uninstaller for V2RayX? My understanding is that it installs a helper to the system and cannot be removed completely simply by removing the GUI app itself as well as:

```
/Library/Application Support/V2RayX
~/Library/Application Support/V2RayX
~/Library/Preferences/cenmrev.V2RayX.plist
```

**Comment by Cenmrev** [comment]
No. Your understanding is wrong. V2RayX will not install or create any other files except the files you mentioned.
