### ISSUE TITLE
建议：增加对shadowsocks aead协议的支持

### ISSUE THREAD

**Issue by ernestyao** [Cenmrev/V2RayX#22]
如题。现在虽然升级支持aead的还不多，但是从近期情况来看似乎是个加强安全性的趋势。建议能早日支持，谢谢！

**Comment by Cenmrev** [comment]
首先如果主要使用 Shadowsocks 协议的话，建议直接使用 SS 的客户端，V2RayX 在短期内都不会增加对 SS 协议的支持。
其次 V2RayX 只是 v2ray-core 的用户界面壳，新的 SS 加密方式不是我能添加的，v2ray-core 所支持的加密方式在[这里](https://www.v2ray.com/chapter_02/protocols/shadowsocks.html)，有问题也请直接向 [v2ray-core](https://github.com/v2ray/v2ray-core) 提交 issue.

**Comment by ernestyao** [comment]
感谢
