### ISSUE TITLE
配置本地 socks5 监听端口后 proxy.pac 没有跟着修改

### ISSUE THREAD

**Issue by soyking** [Cenmrev/V2RayX#220]
请回答下列问题。不按模板发的 issue 将直接被关闭。

0) 如果你没有遇到任何错误和不正常，请在此处回答你想发表的内容：

1) 你正在使用哪个版本的 V2RayX，你的 macOS 系统版本？

1.5.0，10.14.2

2) 如果你在操作 V2RayX 的时候遇到程序崩溃/无反应，请描述你的操作，之后在命令行（终端.app）里运行`/Applications/V2RayX.app/Contents/MacOS/V2RayX`，重复上述操作直至软件崩溃，把终端里的输出贴到下面指定的地方。

```
在这里贴上终端的输出
```

3) 如果 V2RayX 没有发生崩溃，但是有一些不正常行为，比如上次勾选了 mux，再次打开，mux 的钩没有了。请描述你遇到的不正常行为。

在修改了配置中 `Local Socks5 Port` 之后，获取到 proxy.pac 仍然是代理到 1081：

```
curl 127.1:8070/proxy.pac|head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3044  100  3044    0     0   503k      0 --:--:-- --:--:-- --:--:--  594k
var V2Ray = "SOCKS5 127.0.0.1:1081; SOCKS 127.0.0.1:1081; DIRECT;";

var domains = [
	"vpngate.net",
...
```

可能很少人改这个端口？试了几次确实会导致 proxy.pac 不对不能工作

4) 如果 V2RayX 一切正常，但网络依然不如你所预料，请首先把 log level 切换到 debug，再次访问你想访问的网站。然后点击 V2RayX 的 `view current config.json`，将弹出的浏览器内的配置文件粘贴到下面指定的地方，但是隐藏掉ip/端口/id等信息。

```javascript
在这里粘贴配置文件内容
```

然后点击 V2RayX 的`view log`，把 error.log 中的输出贴到下方：

```
在这里贴上 error.log
```

5) 其他你认为可以帮助开发者和你一起解决问题的信息：

**Comment by Cenmrev** [comment]
我都在主界面上写了`If the local port is changed, the pac file also needs manual modification.`，修改了本地端口后，需要 __手动__ 编辑pac。V2RayX 原则上不负责pac文件的正确性，用户自行编辑，自带的pac只是个非常简单的模版。用户编辑过后的pac文件可能很复杂，特别是其中的`FindProxyForURL(url, host)`函数，总不能动用js语法分析器吧...

**Comment by soyking** [comment]
抱歉没注意到下面的字，closed
