### ISSUE TITLE
请问V2RayX怎样配置outbounds的network为kcp

### ISSUE THREAD

**Issue by liqlong** [Cenmrev/V2RayX#227]
请问大家，
配置文件中的：
`"streamSettings": {
        "network": "kcp"
      }`
在V2RayX的可视化界面应该怎么配置呢？

**Comment by Chandler-Lu** [comment]
服务器配置界面右下角的network选项

**Comment by liqlong** [comment]
> 服务器配置界面右下角的network选项

谢谢！
