### ISSUE TITLE
看了默认配置 就代理了 53 80 443 能不能吧这个端口识别去掉

### ISSUE THREAD

**Issue by jackwangshanghai** [Cenmrev/V2RayX#23]
看了默认配置 就代理了 53 80 443 能不能吧这个端口识别去掉

不管什么模式貌似都会加入这个限制 能不能让全部端口都用上

**Comment by soul916** [comment]
patch如下，自己编了一个，测试通过， 终于可以连SSH了。

--- a/V2RayX/config-sample-rules.plist
+++ b/V2RayX/config-sample-rules.plist
@@ -116,38 +116,6 @@
 			<string>IPIfNonMatch</string>
 			<key>rules</key>
 			<array>
-				<dict>
-					<key>outboundTag</key>
-					<string>direct</string>
-					<key>port</key>
-					<string>1-52</string>
-					<key>type</key>
-					<string>field</string>
-				</dict>
-				<dict>
-					<key>outboundTag</key>
-					<string>direct</string>
-					<key>port</key>
-					<string>54-79</string>
-					<key>type</key>
-					<string>field</string>
-				</dict>
-				<dict>
-					<key>outboundTag</key>
-					<string>direct</string>
-					<key>port</key>
-					<string>81-442</string>
-					<key>type</key>
-					<string>field</string>
-				</dict>
-				<dict>
-					<key>outboundTag</key>
-					<string>direct</string>
-					<key>port</key>
-					<string>444-65535</string>
-					<key>type</key>
-					<string>field</string>
-				</dict>
 				<dict>
 					<key>domain</key>
 					<array>
diff --git a/V2RayX/config-sample.plist b/V2RayX/config-sample.plist
index 1f4eb83..a64f32e 100644
--- a/V2RayX/config-sample.plist
+++ b/V2RayX/config-sample.plist
@@ -116,38 +116,6 @@
 			<string>IPIfNonMatch</string>
 			<key>rules</key>
 			<array>
-				<dict>
-					<key>outboundTag</key>
-					<string>direct</string>
-					<key>port</key>
-					<string>1-52</string>
-					<key>type</key>
-					<string>field</string>
-				</dict>
-				<dict>
-					<key>outboundTag</key>
-					<string>direct</string>
-					<key>port</key>
-					<string>54-79</string>
-					<key>type</key>
-					<string>field</string>
-				</dict>
-				<dict>
-					<key>outboundTag</key>
-					<string>direct</string>
-					<key>port</key>
-					<string>81-442</string>
-					<key>type</key>
-					<string>field</string>
-				</dict>
-				<dict>
-					<key>outboundTag</key>
-					<string>direct</string>
-					<key>port</key>
-					<string>444-65535</string>
-					<key>type</key>
-					<string>field</string>
-				</dict>
 				<dict>
 					<key>ip</key>
 					<array>
--

**Comment by Cenmrev** [comment]
现在已经代理全部端口了
