### ISSUE TITLE
请问gfwlist转到pac.js的时候，里面的符号规则是否支持？

### ISSUE THREAD

**Issue by ryougifujino** [Cenmrev/V2RayX#239]
0) 如果你没有遇到任何错误和不正常，请在此处回答你想发表的内容：
gfwlist里面有诸如@，||的符号规则，我写在pac.js的数组里的时候，这些带符号的规则支持吗？
因为我看了一下默认的文件里是没有带符号的，我试着加了几个带符号的规则好像也没有生效。

**Comment by Chandler-Lu** [comment]
不支持，似乎只支持`"example.com",`

**Comment by ryougifujino** [comment]
> 不支持，似乎只支持`"example.com",`

thx
