### ISSUE TITLE
V2RayX 1.5.1 无法第一次运行崩溃

### ISSUE THREAD

**Issue by minosss** [Cenmrev/V2RayX#240]
请回答下列问题。不按模板发的 issue 将直接被关闭。

0) 如果你没有遇到任何错误和不正常，请在此处回答你想发表的内容：

1) 你正在使用哪个版本的 V2RayX，你的 macOS 系统版本？

使用 brew 安装的
v2rayx 1.5.1
macos 10.14.3

2) 如果你在操作 V2RayX 的时候遇到程序崩溃/无反应，请描述你的操作，之后在命令行（终端.app）里运行`/Applications/V2RayX.app/Contents/MacOS/V2RayX`，重复上述操作直至软件崩溃，把终端里的输出贴到下面指定的地方。

```
~/Library/Application Support/V2RayX/cenmrev.v2rayx.v2ray-core.plist: No such file or directory
```

试过删除 V2RayX 文件夹，重新安装后，只有 pac 文件夹和 pac.js 文件
试过 `defaults delete cenmrev.V2RayX` 后重装

密码也都有提示输入

```
(com.apple.xpc.launchd.user.domain.501.104104.Aqua): Could not read path: path = ~/Library/Application Support/V2RayX/cenmrev.v2rayx.v2ray-core.plist, error = 2: No such file or directory
```

之前使用 1.4.x 可以正常使用

**Comment by Chandler-Lu** [comment]
感觉像是`~/Library/Application Support/V2RayX`文件夹的权限问题

**Comment by minosss** [comment]
权限问题的话应该什么文件都没有吧？权限是这个
```
drwxr-xr-x    3 mino  staff    96B Mar 25 21:50 V2RayX
```

**Comment by Chandler-Lu** [comment]
如果不用brew装，直接下载dmg呢

**Comment by minosss** [comment]
试过了，也重新下载1.4试过，也是同样的问题 😂

**Comment by Chandler-Lu** [comment]
emmm，那你可能要等作者了。。我还真没见过这事

**Comment by minosss** [comment]
搞定了~ Orz
看来是卸载的时候没有卸载干净，用的CleanMyMac。
按照 https://github.com/Cenmrev/V2RayX#uninstall 把3个文件夹删除后再来一次就没事了
应该是 `/Library/Application Support/V2RayX` 的问题
