### ISSUE TITLE
routing rules里，各个rules的route to改不了

### ISSUE THREAD

**Issue by ghost** [Cenmrev/V2RayX#243]
请回答下列问题。不按模板发的 issue 将直接被关闭。

0) 如果你没有遇到任何错误和不正常，请在此处回答你想发表的内容：

1) 你正在使用哪个版本的 V2RayX，你的 macOS 系统版本？
V2RayX 1.5.1
macOS 10.14.4

2) 如果你在操作 V2RayX 的时候遇到程序崩溃/无反应，请描述你的操作，之后在命令行（终端.app）里运行`/Applications/V2RayX.app/Contents/MacOS/V2RayX`，重复上述操作直至软件崩溃，把终端里的输出贴到下面指定的地方。

```
在这里贴上终端的输出
```

3) 如果 V2RayX 没有发生崩溃，但是有一些不正常行为，比如上次勾选了 mux，再次打开，mux 的钩没有了。请描述你遇到的不正常行为。
routing rules里，各个rules的route to改不了。比如从main改为direct保存，再打开还是main。
包括自带的rules和新建的rules，都是一样的问题。

4) 如果 V2RayX 一切正常，但网络依然不如你所预料，请首先把 log level 切换到 debug，再次访问你想访问的网站。然后点击 V2RayX 的 `view current config.json`，将弹出的浏览器内的配置文件粘贴到下面指定的地方，但是隐藏掉ip/端口/id等信息。

```javascript
在这里粘贴配置文件内容
```

然后点击 V2RayX 的`view log`，把 error.log 中的输出贴到下方：

```
在这里贴上 error.log
```

5) 其他你认为可以帮助开发者和你一起解决问题的信息：

**Comment by yukixz** [comment]
Same problem.
Configure -> Advanced -> Rules -> route to target doesn't save.

**Comment by nanne007** [comment]
Same problem.

**Comment by y1feng200156** [comment]
对于第三个问题，我试过一个方法，就是修改了 route to 后，先不保存，在选择框内敲下回车，这时再保存就可以了，或者你可以在里面手动输入 main，再敲下回车，同样的效果。

**Comment by X1A0CA1** [comment]
Same problem.
