### ISSUE TITLE
v2ray rules模式下自动启动socks代理而无法启用网页代理（http）

### ISSUE THREAD

**Issue by mzxwt** [Cenmrev/V2RayX#25]
使用v2ray rules模式时会自动在代理中勾选socks代理，而无法使用http代理，强行勾选后也无法使用代理。重启程序或者切换到其他模式后再次使用v2ray rules模式后，仍然只选中socks代理。v2rayw中有可以选择代理模式到切换功能，v2rayx中虽然有设置选项但是好像不起作用。修改config.json中inbound protocol为http后重启程序仍然自动修改为socks。macos下socks似乎支持不是很好，尤其是自带到邮件应用。

**Comment by Cenmrev** [comment]
这个问题应该已经在 https://github.com/Cenmrev/V2RayX/commit/0acad304f9eb049e223c86cfa627c5fe4e44871f 中解决了
