### ISSUE TITLE
大佬作为一个会打中国字的程序猿，可不可以给V2rayX加入官方的中文翻译

### ISSUE THREAD

**Issue by liyuhaolol** [Cenmrev/V2RayX#263]
0) 不太知道您的国籍，不好乱讲，但是我知道您是一个流利的中文使用者，我就是一个简单的希望，我看您源代码都已经在xib文件里进行了简体中文和英文的布局区分了，并且会根据用户的系统语言自动切换简体中文和英文，但是简体中文xib文件没有翻译还是英文。什么时候才能进行多语言的翻译，自动切换或者让用户自己选择语言呢？我知道翻译这玩意是个工作量，但是改一次就基本一劳永逸了啊。说到底咱们这个软件的使用者99%难道不是中国人么？除非身在中国的英文使用者，否则还有谁会用这类软件啊。。。衷心希望作者可以加入中文！

1) 我正在使用V2RayX 1.5.1，你的 macOS 10.14.5

**Comment by nickelzhang** [comment]
原因应该你懂的

**Comment by cnsilvan** [comment]
4个月未更新了。。。大佬是不是喝茶去了。。。
