### ISSUE TITLE
问题：V2Ray X开启V2Ray rule模式及stop后出现Safari访问国内网站极慢的情况

### ISSUE THREAD

**Issue by Loveeatapple** [Cenmrev/V2RayX#27]
·使用场景：使用Safari和chrome访问网站。
  ·问题描述：V2Ray X使用V2Ray rule模式后出现Safari访问国内网站极慢的情况，stop后依然存在该问题，quit后依旧存该问题。在进行 Safari->设置->高级->代理设置->随意点选一个->取消勾选 的操作后恢复正常；Chrome也存在该问题，但比Safari略好。问题于昨晚出现，Google后未能找到解决方案。
  ·操作系统：macOS Sierra 10.12.6 (16G29)
  ·V2Ray X版本：0.7.8 (1)
  ·core版本：2.3.7
  ·网络环境：中国电信，Wi-Fi

**Comment by afboyxiyang** [comment]
我也遇到了这种问题，不知道为何
