### ISSUE TITLE
使用V2Ray Rules模式后，访问百度使用了代理而不是直连。

### ISSUE THREAD

**Issue by Summerlve** [Cenmrev/V2RayX#29]
访问百度的时候还是用了代理，好像chinasites direct没有生效，或者有可能是这条baidu的ip没有加到chinasites中？
能不能添加一个pac模式呢，像shadowsocks客户端那样，可以更新pac文件的。

**Comment by uloongme** [comment]
一直都有这个功能啊
<img width="267" alt="qq20171011-205342 2x" src="https://user-images.githubusercontent.com/3370606/31441679-85bbbb80-ae59-11e7-9548-066be8bdfd80.png">

**Comment by Summerlve** [comment]
不好意思，发错repo了，我想发在v2rayw上的......看错一个字母= =。
