### ISSUE TITLE
无法导入json配置文件

### ISSUE THREAD

**Issue by SivanCola** [Cenmrev/V2RayX#293]
导入从windows端导出的json文件，直接显示“tag direct is reserved, please use another one!”，手动更换后还是报出同样的错误！望解决

**Comment by baiping-prog** [comment]
你看下你这个里面
![image](https://user-images.githubusercontent.com/17891796/66898658-2d416b00-f02c-11e9-97c8-6e252e517571.png)
是不是有一条叫direct的，把它删了就好了。

**Comment by SivanCola** [comment]
导入json后有你说的位置有一条block，一条direct。删除后，点击finish确实可以保存了，但是软件会退出。手动打开后，又恢复到没有导入json之前的状态了~

**Comment by SivanCola** [comment]
我又测试了下，把json文本中direct部分删除掉，发现可以导入，但是点击ok后软件闪退。再次打开，软件配置还是初始状态。

**Comment by XGCoder** [comment]
> 我又测试了下，把json文本中直接部分删除掉，发现可以导入，但是点击确定后软件闪退。再次打开，软件配置还是初始状态。

大兄嘚,这是如何解决的,或者后期有解决方法还请回来回复一下哈

**Comment by SivanCola** [comment]
> > 我又测试了下，把json文本中直接部分删除掉，发现可以导入，但是点击确定后软件闪退。再次打开，软件配置还是初始状态。
> 
> 大兄嘚,这是如何解决的,或者后期有解决方法还请回来回复一下哈

在原始的json中，保留“outbounds”、"routings”字段，其它删除即可。

**Comment by SivanCola** [comment]
在原始的json中，保留“outbounds”、"routings”字段，其它删除即可导入。

**Comment by XGCoder** [comment]
> > > 我又测试了下，把json文本中直接部分删除掉，发现可以导入，但是点击确定后软件闪退。再次打开，软件配置还是初始状态。
> > 
> > 
> > 大兄嘚,这是如何解决的,或者后期有解决方法还请回来回复一下哈
> 
> 在原始的json中，保留“outbounds”、"routings”字段，其它删除即可。

emmmm,大兄嘚,原有的json中就没有"routings”字段,我删除到只剩下“outbounds”字段,导入后还是一样,崩溃 ...

**Comment by SivanCola** [comment]
让我想想当时具体怎么操作的，最近事情有些多，具体的方式我也忘记了。

**Comment by pro4jhu** [comment]
我搞定了,在json内容中搜索tag, 会搜索出很多结果,将每个的冒号后双引号里面的值加上任意字符就行了,全部修改为加11,比如原来是direct,修改后为direct11
