### ISSUE TITLE
V2RayX cannot work for ftp?

### ISSUE THREAD

**Issue by smcduck** [Cenmrev/V2RayX#3]
I have installed lastest v2rayx in macbook, config as global mode, it works well for visiting websites such like google.com. **_But it seems like not work for ftp**_.

my shell command:
curl -f -L -- "ftp://ftp.videolan.org/pub/videolan/contrib/x86_64-apple-darwin10/vlc-contrib-x86_64-apple-darwin10-latest.tar.bz2" > "vlc-contrib-x86_64-apple-darwin10-latest.tar.bz2"

Download speed very slow, **_the speed is the same as v2rayx is closed.  I use this command in my vps in japan, the download speed is very very high.**_

Then I try to download it in chrome, **_the chrome says: ERR_NO_SUPPORTED_PROXIES**_

After that, I change v2rayx config to "auto mode", add "videolan.org" to pac.js, and restart v2rayx. Chrome can download than ftp url, but speed is still very slow. Seems like v2ray(x) works not well for ftp. The speed should be very good.

**Comment by Cenmrev** [comment]
I think you may be right. I tried `curl -f -L --socks5-host 127.0.0.1:1081 -- "ftp://ftp.videolan.org/pub/videolan/contrib/x86_64-apple-darwin10/vlc-contrib-x86_64-apple-darwin10-latest.tar.bz2" > "vlc-contrib-x86_64-apple-darwin10-latest.tar.bz2"` but no download speeds. It should be v2ray-core that does not support ftp. You may open an issue [here](https://github.com/v2ray/v2ray-core/issues).
However, the option `--socks5-host 127.0.0.1:1080` worked when I tried ShadowsocksX. So you can temporarily download your file by shadowsocks.
Also, it is necessary to point out that auto and global modes work only when you are using an cocoa application, like Safari.app or Twitter.app, which obeys macOS's proxy settings. Shell commands usually do not obey system proxy rules. For curl, you can specify the option `--socks5-host hostname:port` to use a socks5 proxy.

**Comment by Cenmrev** [comment]
I have added the option "allowPassive" to the [newest version](https://github.com/Cenmrev/V2RayX/releases/tag/v0.4). At least on my personal mac, there is no problem to download that file using curl and v2rayx now. 
But Chrome still says ERR_NO_SUPPORTED_PROXIES. I have no idea about this.

**Comment by v2ray** [comment]
Chrome probably tries to use Socks proxy with BIND request for passive FTP connection. V2Ray's socks implementation doesn't support this mode.

**Comment by JerryCui** [comment]
I tried with shadowsocksX, it worked. @Cenmrev @nifflerfox
