### ISSUE TITLE
Http伪装

### ISSUE THREAD

**Issue by Vywh** [Cenmrev/V2RayX#31]
V2RayX GUI界面似乎没有办法修改http伪装的header（或者根本不支持http伪装？）

**Comment by giveup** [comment]
http伪装由v2ray-core支持，V2RayX只是GUI，不存在支不支持的问题。
需要手动配置config。

**Comment by Vywh** [comment]
Config由gui管理，手动修改没有效果，V2rayX开启后会恢复手动修改之前

**Comment by Cenmrev** [comment]
已经支持。 https://github.com/Cenmrev/V2RayX/commit/8d62d28a2119a084aba6be8fe573c64d322aff5a
