### ISSUE TITLE
第一次运行出现Sorry, unknown settings!问题

### ISSUE THREAD

**Issue by wonderffee** [Cenmrev/V2RayX#32]
手上有两台Mac同样的系统，都是10.12，一台运行是正常的，也能用Chrome上网。另一台刚开始运行V2RayX时有一个提示，忘了是什么，点了之后然后提示这个：
Sorry, unknown settings!
All V2RayX settings will be reset.
在Chrome中打开Google提示：代理服务器出现问题，或者地址有误。

执行"defaults delete cenmrev.V2RayX"命令再试也是一样的错误提示
求助这是为什么，明明一样的配置两台的表现不一样，看了源码还是不明所以

**Comment by Cenmrev** [comment]
请在有问题的机器上删除以下文件
/Library/Application Support/V2RayX
~/Library/Application Support/V2RayX
~/Library/Preferences/cenmrev.V2RayX.plist
并执行"defaults delete cenmrev.V2RayX"。
然后再打开 V2RayX 测试。测试时请记录下 V2RayX 提示了什么。如果还是有问题，请反馈 V2RayX 提示了什么。谢谢。

**Comment by wonderffee** [comment]
按照步骤做了，是这个提示：V2RayX needs to install a small tool to /Library/Application Support/V2RayX/ with administrator privileges to set system proxy quickly.
我点了Install，也输了密码，然后就会提示上面的Sorry, unknown settings!问题

**Comment by Cenmrev** [comment]
第一次运行会出现“Sorry, unknown settings!”是正常的，因为确实没有预置的配置信息。在 configure 页面里面填写好你自己的服务器信息后 V2RayX 能正常工作了吗？

**Comment by wonderffee** [comment]
是家里的Mac上有这个问题，只能等今晚了，但工作用的Mac上完全没这个问题啊，用默认自带的Test server就能正常上网，就是对这个特别不解

**Comment by wonderffee** [comment]
在Configure里勾选share over lan居然就可以上网了，使用的还是默认的测试服务器

**Comment by tinpont** [comment]
Sorry, unknown settings!
All V2RayX settings will be reset.

macOS 10.13相同问题
