### ISSUE TITLE
添加了一个Subscribe，应用启动不了了，删除配置重新安装也不行

### ISSUE THREAD

**Issue by airc-ccc** [Cenmrev/V2RayX#334]
### 问题描述
```
刚安装上V2RayX，点击Advanced，添加了一个Subscribe, 然后点击OK，应用关闭了，然后启动不了了。

使用AppClear卸载应用以后，在次通过压缩包解压App，重新安装也不行， 再次卸载App,  删除配置文件`~/Library/Preferences/cenmrev.V2RayX.plist`, 重新安装，还是不行，同样的错误输出
```
### 目前使用的系统以及V2RayX版本
MacOS: BigSur 11.1
V2RayX: 1.5.1

### 控制台输出
```
Assertion failed: (decodedString != nil), function +[ConfigImporter decodeBase64String:], file /Users/travis/build/Cenmrev/V2RayX/V2RayX/ConfigImporter.m, line 24.
```

**Comment by ztony0712** [comment]
相同版本出现了同样的问题，不知道是不是不支持vless订阅的问题

**Comment by 016** [comment]
我来提供一个解决办法，使用 app delete 拖入这个程序，然后别急着点删除，
观察一下列表，找到 /Users/xxxx/Caches/cenmrev.V2RayX 把这个删除掉，再启动一次看看
如果还是不行，找到pac.js 备份，除了 /Applications/V2RayX.app以外都删除掉，会提示重装，把pac复制回来，就可以了。

貌似因为缓存的原因，会在更新订阅的时候奔溃，这已经是我最近12个月里遇到的第三次了，这次研究了一下。

希望对后来者有帮助
