### ISSUE TITLE
release version not support OSX 10.10 default

### ISSUE THREAD

**Issue by zysuper** [Cenmrev/V2RayX#4]
Hi,I compile source code in OSX 10.10，it's work.Why release version use high compile system version?

**Comment by Cenmrev** [comment]
Thank you for your suggestion. I tried compiling wth deployment target 10.8 and Xcode gave no issues. However I do not have a 10.8 test platform, so I am not sure if this will cause bugs.
By the way, I supposed that most Mac users are using the latest OS X version so I had not considered backward compatibility. Actually I did not know anything about backward compatibility.

感谢你的建议。我尝试在把 deployment target 直接调到 10.8，Xcode 编译通过。但我没有 10.8 的测试平台所以我也不知道这样会不会产生bug。另外我之前认为大部分用户应该都在用最新系统，所以就没有考虑过向后兼容的问题。事实上我也不知道怎么向后兼容。

https://github.com/Cenmrev/V2RayX/commit/4cc933edbf17a8f3a61c3e4d428cefd7fd773790
