### ISSUE TITLE
macOS 10.13.1下界面和运行均不正常

### ISSUE THREAD

**Issue by RedDragonFalcon1** [Cenmrev/V2RayX#42]
使用场景：macOS 10.13.1
问题描述：macOS 10.13.1下界面和运行均不正常，包括：
1、菜单栏上的图标消失；
2、开启和关闭显示为Item 1和Item 2
3、Servers菜单无法展开
4、配置无法保存
5、无法选择工作模式
软件版本：0.7.9

**Comment by Cenmrev** [comment]
请试试新版本行不行 https://github.com/Cenmrev/V2RayX/releases/tag/0.9

**Comment by Portan** [comment]
上面的链接里没有程序

**Comment by Portan** [comment]
新版程序已经好用了
