### ISSUE TITLE
Easy Switching among TLS servers or non-TLS servers

### ISSUE THREAD

**Issue by flipphos** [Cenmrev/V2RayX#44]
On version 0.7.9(1) TLS is supported, This is nice.
However, every time I switch to another TLS server, I have to change the Server Name in the "transport settings". Or if I switch to another non-TLS server, I have to un-check the "Use TLS" option in the "transport settings".

It seems that the "transport settings" are global settings, which doesn't seems to be a good idea, as different servers would have different settings. It would be better for the transport settings attached to each server and not being a global one.

**Comment by laoyur** [comment]
agree.
TLS / WS setting should be per-server, rather than global settings.

**Comment by Cenmrev** [comment]
Please try https://github.com/Cenmrev/V2RayX/releases/tag/v0.9 and report bugs.
Thank you!

**Comment by laoyur** [comment]
it works
