### ISSUE TITLE
Version for Linux-based operating systems

### ISSUE THREAD

**Issue by baimafeima** [Cenmrev/V2RayX#45]
Would this also work for Linux-based operating systems?

**Comment by Cenmrev** [comment]
v2ray: Yes, see https://github.com/v2ray/v2ray-core/releases/tag/v2.47
V2RayX: No.

**Comment by baimafeima** [comment]
@Cenmrev Thanks for the quick reply. I didn't find any suitable client though. V2ray-core is only server software isn't it?

**Comment by Cenmrev** [comment]
@baimafeima The client and server versions of v2ray-core are  the same, totally dependent on your config file. See [Official Manual](https://v2ray.com/chapter_01/install.html).
