### ISSUE TITLE
间歇性连不上

### ISSUE THREAD

**Issue by leewi9** [Cenmrev/V2RayX#46]
平常用的用好的，但是总是隔一段时间就连不上，要断开wifi再重连就可以了，希望能加强下代码质量。

**Comment by leewi9** [comment]
经过反复实验，感觉原因应该是并发的问题，当我一次性打开20个国外网站，其中一些页面就会一直在加载，再尝试打开google等就打不开，再尝试重启v2rayx就恢复正常了，可以打开了。

**Comment by Cenmrev** [comment]
网络连接部分不是 V2RayX 的职责，本程序只提供用户界面，具体的网络操作由 v2ray-core 完成，请去 https://github.com/v2ray/v2ray-core 反馈。
