### ISSUE TITLE
MAC OS卸载后再次安装后，无法正常运行使用了

### ISSUE THREAD

**Issue by ilovebamboo** [Cenmrev/V2RayX#47]

**Comment by ilovebamboo** [comment]
![qq20171117-200329](https://user-images.githubusercontent.com/6214084/32946443-85cb66c0-cbd2-11e7-92c5-ce9830217f83.png)
![qq20171117-200311](https://user-images.githubusercontent.com/6214084/32946444-85fcea1a-cbd2-11e7-8d4d-6eeb203d2c41.png)

**Comment by Cenmrev** [comment]
第一次运行 V2RayX 都会出现这两条信息，正常。请提供更多“无法正常运行使用了”的症状。

**Comment by heke2929** [comment]
更新最新版解决了问题, 谢谢~ @Cenmrev

**Comment by afboyxiyang** [comment]
但我感觉还是3.1版本不错，最新的我的反而连不上

**Comment by ilovebamboo** [comment]
没有用 ，重新安装 还是一样
