### ISSUE TITLE
建议：手动编辑或导入config.json

### ISSUE THREAD

**Issue by ttimasdf** [Cenmrev/V2RayX#48]
用了V2RayX以后似乎outbound只能用vmess了，而我暂时没有机器可以搭v2，想接入ss作为服务端。请问可以提供一些配置更灵活的方式吗？比如标记一个profile就是手工导入的，在配置窗口中只给一个按钮打开Jayson或其他什么文本编辑器，这样会不会更灵活一些？
我的想法和 #14 有些类似，但是觉得兼容原生json会不会更好实现一些？

**Comment by Anthonyeef** [comment]
see: https://github.com/Cenmrev/V2RayX/issues/67

**Comment by Cenmrev** [comment]
see https://github.com/Cenmrev/V2RayX/commit/a1ef56779104f5852c6cb29c73caebc4a025e91a
