### ISSUE TITLE
直接替换最新的macos里的v2ray执行程序完全不兼容！

### ISSUE THREAD

**Issue by afboyxiyang** [Cenmrev/V2RayX#49]
作者什么时候有空的时候升级一下吧，都到3.X了，目录中的程序根本不能直接替换升级。
感谢您的付出和劳动！
THX

**Comment by Cenmrev** [comment]
https://github.com/Cenmrev/V2RayX/releases/tag/v0.8
简单做了下适配，希望提供反馈。谢谢！

**Comment by afboyxiyang** [comment]
已经安装，正在使用当中……
能否增加一项添加规则的选项，目前选用 v2ray rules 国内的的站点速度慢！
选用PAC模式也不快，中国联通！

**Comment by Cenmrev** [comment]
你可以编辑 pac 文件来控制哪些网站直连哪些网站走 v2ray. 自带的pac里只有规定了少量网站走 v2ray.

**Comment by afboyxiyang** [comment]
编辑simple.pac文件，太多的地址要编辑了……
非常感谢您的解答
