### ISSUE TITLE
能否自定义路由规则，贴近v2ray原生的规则模式

### ISSUE THREAD

**Issue by fax001** [Cenmrev/V2RayX#5]
v2ray原生支持部分域名或者ip走某个指定代理的功能
但是在V2RayX中貌似不行，只能通过gui添加运行配置，不支持自定义的其他路由规则

**Comment by Cenmrev** [comment]
意思是需要自定义config.json中的routing部分吗？目前确实不能做到，况且 v2ray 自带的 chinaip 和 chinasite 规则已经挺够用了。
如果你需要完全自定义routing部分，可以自己修改 V2Ray.app/Contents/Resources/config-sample-rules.plist，这个文件和 config.json 结构一样，用 Xcode 打开编辑。然后选择 V2RayX 的 V2Ray Rules 运行模式即可。

**Comment by fax001** [comment]
@Cenmrev 好的 我尝试下

**Comment by avk458** [comment]
麻烦不要回复全部

2016年11月4日星期五，luomo <notifications@github.com> 写道：
