### ISSUE TITLE
频繁提示“v2rayx_sysconnf”正在尝试修改系统网络配置。0.8版本。

### ISSUE THREAD

**Issue by Ivan97** [Cenmrev/V2RayX#51]
0.8版本。
频繁提示“v2rayx_sysconnf”正在尝试修改系统网络配置。
不知道哪里有问题。
我进到包内容下给这个文件777权限也不行。
![1101513238713_ pic_hd](https://user-images.githubusercontent.com/10104255/33981646-a889fd22-e0e8-11e7-89d0-eb1ac8ab13a7.jpg)

**Comment by Cenmrev** [comment]
退出 V2RayX，删掉 `/Library/Application Support/V2RayX/`。重新打开 V2RayX 并输入管理员密码。
或者运行
```
sudo chown root:admin "/Library/Application Support/V2RayX/v2rayx_sysconf"
sudo chmod +s "/Library/Application Support/V2RayX/v2rayx_sysconf"
```

**Comment by Ivan97** [comment]
问题解决了
