### ISSUE TITLE
使用v2rayx生成的config无法使v2ray(X)正常工作

### ISSUE THREAD

**Issue by Zieng** [Cenmrev/V2RayX#52]
环境：
OS：macOS 10.13.2
v2rayx: Version 0.9 (1)
--------------------------------------

无法使用进行科学上网，而手机通过shadowrocket可以正常使用，所以可以确定服务器配置没有问题。（PS：服务器配置基本就是默认配置）
将v2rayx生成的config文件导出，使用此配置文件运行v2ray，仍然无法科学上网。
经测试，将此config中的某些配置参数删除可以正常连接。

v2rayx生成的config
```
"outbound" : {
    "sendThrough" : "0.0.0.0",
    "mux" : {
      "enabled" : true,
      "concurrency" : 8
    },
    "protocol" : "vmess",
    "settings" : {
      "vnext" : [
        {
          "address" : "my-sever-ip",
          "port" : my-server-port,
          "users" : [
            {
              "id" : "my-uuid",
              "alterId" : 64,
              "security" : "aes-128-cfb",
              "level" : 1
            }
          ],
          "remark" : "remark"
        }
      ]
    },
    "streamSettings" : {
      "network" : "tcp",
      "tcpSettings" : {
        "header" : {
          "type" : "none"
        },
        "connectionReuse" : true
      },
      "kcpSettings" : {
        "header" : {
          "type" : "none"
        },
        "mtu" : 1350,
        "congestion" : false,
        "tti" : 50,
        "uplinkCapacity" : 5,
        "writeBufferSize" : 1,
        "readBufferSize" : 2,
        "downlinkCapacity" : 20
      },
      "security" : "tls",
      "tlsSettings" : {
        "serverName" : "",
        "allowInsecure" : false
      },
      "wsSettings" : {
        "path" : "",
        "connectionReuse" : true
      }
    }
  }
```
删除部分参数可正常使用的
```
"outbound" : {
    "protocol" : "vmess",
    "settings" : {
      "vnext" : [
        {
          "address" : "my-sever-ip",
          "port" : my-server-port,
          "users" : [
            {
              "id" : "my-uuid",
              "alterId" : 64,
              "security" : "aes-128-cfb",
              "level" : 1
            }
          ],
          "remark" : "remark"
        }
      ]
    }
  }
```
这些多余的参数是由v2rayx的configure窗口中transport setting生成的，问题是这些参数哪怕手动删除之后，仍会自动生成出来。

**Comment by Cenmrev** [comment]
抱歉，transport setting 部分还有 bug 我没修完，请先用旧版本。

**Comment by Cenmrev** [comment]
@Zieng 可以的话能不能帮我测试下，把你贴出的第一份配置文件中，`"security" : "tls"` 改成 `"security" : "none"`, mux 下面的 `"enabled" : true,` 改成 `"enabled" : false,`，其他不变，测试能否正常使用？

**Comment by Zieng** [comment]
> 可以的话能不能帮我测试下，把你贴出的第一份配置文件中，"security" : "tls" 改成 "security" : "none", mux 下面的 "enabled" : true, 改成 "enabled" : false,，其他不变，测试能否正常使用？

@Cenmrev 试了下，可以👍🏻

**Comment by Cenmrev** [comment]
@Zieng 发了个新版本，帮忙测试下现在有没有问题吧 https://github.com/Cenmrev/V2RayX/releases/tag/v0.9.1

**Comment by Zieng** [comment]
@Cenmrev 刚测过了，还是不行。生成的config中仍有`"security" : "tls"`和mux下的`"enabled" : true`。经测试，只需要把`"security" : "tls"`改为`"security" : "none"`就能正常工作，看来与mux是否enable无关。

**Comment by Zieng** [comment]
不能直接关掉transport setting部分的config生成吗？感觉加一个选项来控制是否执行transport setting就行了。

**Comment by Cenmrev** [comment]
@Zieng 你在 transport setting 里面把 TLS -> use tls 的选项去掉再试一下

**Comment by Zieng** [comment]
@Cenmrev 不好意思，现在才看到你又回复了。试过去掉use tls，仍然不行。最近都是用的老版本的。
