### ISSUE TITLE
经由GUI配置并启用后无法代理

### ISSUE THREAD

**Issue by alexwwang** [Cenmrev/V2RayX#53]
无论是pac模式、全局模式还是手动模式，都无法正常代理
日志中有访问的记录，但是浏览器提示CONNECTION_CLOSED
transport settings中的tls设置和mux设置无法enable，不知道什么毛病
系统：macos 10.10.5
浏览器：chrome 6x
代理方式：switchyomega 和 系统pac

**Comment by Cenmrev** [comment]
#52

**Comment by Cenmrev** [comment]
请帮忙测试下这个版本是否可以正常使用。https://github.com/Cenmrev/V2RayX/releases/tag/v0.9.1

**Comment by Portan** [comment]
我这边用了0.9.1可以正常使用了

**Comment by since2004** [comment]
你的配置有问题吧？我目前用了证书，一切是正常的

**Comment by alexwwang** [comment]
很奇怪，虽然配置阶段各环节都能正常保存配置了，但是启用后，浏览器仍然提示 ERR_CONNECTION_CLOSED
而且我用3.5版的core也是一样的问题。
同样的配置在windows、linux和10.9的系统上都正常。

**Comment by alexwwang** [comment]
update：迫不得以我把系统升级到High Sierra后，问题解决，已经可以正常使用。苹果药丸。

**Comment by since2004** [comment]
这跟系统没关系吧。。。

**Comment by alexwwang** [comment]
I thought not but the fact shows that does.

**Comment by since2004** [comment]
好吧，最终解决就行了

**Comment by alexwwang** [comment]
我怀疑是网络部分的某些设置可能被搞坏了，因为有请求出去，但是返回的数据进不了chrome。
