### ISSUE TITLE
把0.8(1)版本的配置填写到0.9.1版本无法访问墙外网站

### ISSUE THREAD

**Issue by HellerLu** [Cenmrev/V2RayX#55]
在0.9.1版本里填入与0.8(1)版本相同的信息后出现无法代理，换回0.8(1)版本,正常使用
系统版本：10.13.2

**Comment by Cenmrev** [comment]
V2RayX 现在已经可以记录 v2ray 的 log 了，请至少把 log 发上来。
另外请重置一下 transport settings 试试。

**Comment by HellenLu** [comment]
2018/01/15 09:19:00 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:1081
2018/01/15 09:19:00 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:8001
2018/01/15 09:19:00 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:1081
2018/01/15 09:19:00 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:8001
2018/01/15 09:19:00 [Warning]: Core: V2Ray started
2018/01/15 09:22:08 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:1080
2018/01/15 09:22:08 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:80
2018/01/15 09:22:08 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:1080
2018/01/15 09:23:31 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:1080
2018/01/15 09:23:31 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:80
2018/01/15 09:23:31 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:1080
2018/01/15 09:23:40 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:1080
2018/01/15 09:23:40 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:80
2018/01/15 09:23:40 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:1080
2018/01/15 09:30:25 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:1080
2018/01/15 09:30:25 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:80
2018/01/15 09:30:25 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:1080
2018/01/15 09:30:25 [Info]: Transport|Internet|UDP: listening UDP on 127.0.0.1:1080
2018/01/15 09:30:48 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:1080
2018/01/15 09:30:48 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:80
2018/01/15 09:30:48 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:1080
2018/01/15 09:30:48 [Info]: Transport|Internet|UDP: listening UDP on 127.0.0.1:1080

{
  "policy" : {
    "levels" : {
      "0" : {
        "uplinkOnly" : 0
      }
    }
  },
  "dns" : {
    "servers" : [
      "localhost"
    ]
  },
  "outboundDetour" : [
    {
      "protocol" : "freedom",
      "tag" : "direct",
      "settings" : {

      }
    },
    {
      "tag" : "transit",
      "protocol" : "socks",
      "settings" : {
        "servers" : [
          {
            "address" : "www.hellensu.com",
            "port" : 443
          }
        ]
      }
    }
  ],
  "inbound" : {
    "listen" : "127.0.0.1",
    "port" : 1080,
    "protocol" : "socks",
    "settings" : {
      "auth" : "noauth",
      "udp" : true,
      "ip" : "127.0.0.1"
    }
  },
  "inboundDetour" : [
    {
      "listen" : "127.0.0.1",
      "allocate" : {
        "strategy" : "always",
        "refresh" : 5,
        "concurrency" : 3
      },
      "port" : 80,
      "protocol" : "http",
      "tag" : "httpDetour",
      "domainOverride" : [
        "http",
        "tls"
      ],
      "streamSettings" : {

      },
      "settings" : {
        "timeout" : 0
      }
    }
  ],
  "log" : {
    "error" : "\/var\/folders\/_l\/w23rh31s1j78lnsrlxk3mq0m0000gn\/T\/cenmrev.v2rayx.log.08B1B152-2BE9-4B19-9A9D-F1BB0865DF91\/error.log",
    "loglevel" : "debug",
    "access" : "\/var\/folders\/_l\/w23rh31s1j78lnsrlxk3mq0m0000gn\/T\/cenmrev.v2rayx.log.08B1B152-2BE9-4B19-9A9D-F1BB0865DF91\/access.log"
  },
  "routing" : {
    "strategy" : "rules",
    "settings" : {
      "domainStrategy" : "IPIfNonMatch",
      "rules" : [
        {
          "port" : "1-52",
          "type" : "field",
          "outboundTag" : "direct"
        },
        {
          "port" : "54-79",
          "type" : "field",
          "outboundTag" : "direct"
        },
        {
          "port" : "81-442",
          "type" : "field",
          "outboundTag" : "direct"
        },
        {
          "port" : "444-65535",
          "type" : "field",
          "outboundTag" : "direct"
        },
        {
          "type" : "field",
          "ip" : [
            "0.0.0.0\/8",
            "10.0.0.0\/8",
            "100.64.0.0\/10",
            "127.0.0.0\/8",
            "169.254.0.0\/16",
            "172.16.0.0\/12",
            "192.0.0.0\/24",
            "192.0.2.0\/24",
            "192.168.0.0\/16",
            "198.18.0.0\/15",
            "198.51.100.0\/24",
            "203.0.113.0\/24",
            "::1\/128",
            "fc00::\/7",
            "fe80::\/10",
            "geoip:cn"
          ],
          "outboundTag" : "direct"
        },
        {
          "type" : "field",
          "outboundTag" : "direct",
          "domain" : [
            "geosite:cn"
          ]
        }
      ]
    }
  },
  "outbound" : {
    "sendThrough" : "0.0.0.0",
    "proxySettings" : {
      "tag" : "transit"
    },
    "mux" : {
      "enabled" : false,
      "concurrency" : 8
    },
    "protocol" : "vmess",
    "settings" : {
      "vnext" : [
        {
          "address" : "www.hellensu.com",
          "port" : 443,
          "users" : [
            {
              "id" : "dbe1debc-b5d3-42f6-aa78-5dd9b1a4df9e",
              "alterId" : 64,
              "security" : "aes-128-cfb",
              "level" : 0
            }
          ],
          "remark" : "pump"
        }
      ]
    },
    "streamSettings" : {
      "network" : "tcp",
      "tcpSettings" : {
        "header" : {
          "type" : "http"
        },
        "connectionReuse" : true
      },
      "kcpSettings" : {
        "header" : {
          "type" : "none"
        },
        "mtu" : 1350,
        "congestion" : false,
        "tti" : 50,
        "uplinkCapacity" : 5,
        "writeBufferSize" : 1,
        "readBufferSize" : 2,
        "downlinkCapacity" : 20
      },
      "security" : "none",
      "tlsSettings" : {
        "serverName" : "www.hellensu.com",
        "allowInsecure" : false
      },
      "wsSettings" : {
        "path" : "",
        "connectionReuse" : true
      }
    }
  }
}
