### ISSUE TITLE
macOS 10.13.2 每次启动或者切换模式会提示要授权

### ISSUE THREAD

**Issue by XGHeaven** [Cenmrev/V2RayX#58]
<img width="443" alt="qq20180121-134029 2x" src="https://user-images.githubusercontent.com/9291212/35191231-ab3d8f30-feb0-11e7-815d-81b110b75397.png">

系统版本： macos 10.13.2
V2rayX 版本：0.9.1(1)

我试过 README 当中 default 的那个命令了，但是还是没有效果，依旧会弹出来这个提示。
但是之前的旧版本没有问题。

**Comment by jackwangshanghai** [comment]
我也是 不管干啥都有这提示

**Comment by czhiling** [comment]
找到了解决办法：

Terminal下运行程序目录 "/Applications/V2RayX.app/Contents/Resources"下的“install_helper.sh”

`bash ./install_helper.sh`

**Comment by XGHeaven** [comment]
@czhiling Good，问题修复。只能希望作者赶紧修复这个 bug。
