### ISSUE TITLE
v0.9.2版无法通过Homebrew-Cask.下载

### ISSUE THREAD

**Issue by tinpont** [Cenmrev/V2RayX#65]
Log
```shell
brew cask install v2rayx
Updating Homebrew...
==> Satisfying dependencies
==> Downloading https://github.com/Cenmrev/V2RayX/releases/download/v0.9.1/V2Ray
######################################################################## 100.0%
==> Verifying checksum for Cask v2rayx
==> Installing Cask v2rayx
==> Moving App 'V2RayX.app' to '/Applications/V2RayX.app'.
🍺  v2rayx was successfully installed!
```

下载到的是0.9.1，3月5日测试

**Comment by daizy008** [comment]
我下下来的也是 0.91

**Comment by uloongme** [comment]
现在貌似不提供预编译版本了，需要自己下载源代码在本地编译之后使用。我编译之后界面显示还是0.9.1，但是看git tag确实是0.9.2了。

**Comment by KngEast** [comment]
我也是编译出来还是0.9.1

**Comment by afboyxiyang** [comment]
本地编译不在行啊

**Comment by sagexy** [comment]
clone源代码后手动把Info.plist文件中的版本号改下就行了
	<key>CFBundleShortVersionString</key>
	<string>0.9.2</string>

**Comment by afboyxiyang** [comment]
==> Satisfying dependencies
==> Downloading https://github.com/Cenmrev/V2RayX/releases/download/v0.9.1/V2Ray
######################################################################## 100.0%
curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Operation timed out
######################################################################## 100.0%
==> Verifying checksum for Cask v2rayx
==> Installing Cask v2rayx
==> Moving App 'V2RayX.app' to '/Applications/V2RayX.app'.
🍺  v2rayx was successfully installed!

**Comment by tinpont** [comment]
现在已经可以通过brew下载到最新版了。
