### ISSUE TITLE
有没有批量添加配置文件的方式？

### ISSUE THREAD

**Issue by ifsc01** [Cenmrev/V2RayX#67]

**Comment by Anthonyeef** [comment]
找了一下，存放配置的路径应该在这里： `/Users/你的用户名/Library/Application Support/V2RayX/config.json` 

使用 GUI 添加了一个配置后，打开这个 config 文件复制粘贴应该就可以了。

**Comment by zw0** [comment]
现在换成多开v2ray-core了 http://dsh.li/blog/15211070423079.html
