### ISSUE TITLE
google 备份与同步，网盘。不能通过V2RayX直接代理

### ISSUE THREAD

**Issue by seven76six** [Cenmrev/V2RayX#68]
需要配合Proxifier一起用才行。但是，ShadowsocksX-NG-R白名单就可以直接用。

**Comment by ImHUan** [comment]
我也遇到这个问题，然后各种研究，发现把系统代理里http勾上配置好，google备份 就好用了。具体看下图
![image](https://user-images.githubusercontent.com/385914/39090550-a2004254-4614-11e8-906f-939db79acf86.png)

**Comment by seven76six** [comment]
你采用的是什么模式，V2RayX开启的时候就会自动在代理这里设置好打勾了。不需要手动。现在0.9.2版本应该可以用了

**Comment by ImHUan** [comment]
- global 模式
- 开启的时候会在socks代理打勾，因为我是vmess，http我都是手动勾上并填写的
- 我的rules用chrome的omega swith 实现
@seven76six

**Comment by Cenmrev** [comment]
经过测试，https://github.com/Cenmrev/V2RayX/commit/e171cabfcf4c0a2afed86912b5dc08ff40da2ea8 之后， [Backup and Sync from Google.app](https://www.google.com/drive/download/) 在 rules 模式下应该已经可以用了。pac 模式+自带的简单pac也测试通过。
