### ISSUE TITLE
请问ws+tls http伪装的时候应该怎么填写？windows使用正常

### ISSUE THREAD

**Issue by ColeHou** [Cenmrev/V2RayX#71]
![](https://ws2.sinaimg.cn/large/006tKfTcly1fpno4z42snj30qy0d23zh.jpg)
![](https://ws2.sinaimg.cn/large/006tKfTcly1fpno5b5i8wj30qk0dqq4a.jpg)

就是这两个地方怎么填？那个tls中的Service name 填什么？配置文件中的host吗？

**Comment by sdnsalon** [comment]
server name  是域名， path 就填你服务端设置的path

**Comment by ColeHou** [comment]
还是不行啊，http头部伪装的，你的可以吗

**Comment by Cenmrev** [comment]
新版已经支持自定义 ws 的 `headers` 字段。
