### ISSUE TITLE
Ask for "Import configuration from URL or QR-Code" 

### ISSUE THREAD

**Issue by BrandoZhang** [Cenmrev/V2RayX#73]
Current V2RayX cannot import configuration from URL (URL that starts with vmess://) or QR code, which is inconvenient.

**Comment by gutenye** [comment]
It's a very very useful feature.

**Comment by Cenmrev** [comment]
I do not find any instructions or standards for generating or parsing vmess:// and QR code on V2Ray's official site [v2ray.com](v2ray.com). Can you please tell me where you saw these URLs and do you know according to what kind of standards they are generated? Thanks.

**Comment by BrandoZhang** [comment]
When I use Windows, there is an available version forked from [Jrohy/V2RayN](https://github.com/Jrohy/v2rayN/releases) can make it.
A brief introduction can be found in [V2Ray/VMess](https://www.v2ray.com/eng/protocols/vmess.html).

**Comment by hadifarnoud** [comment]
what happened to this feature? does anyone know how can I convert a vmess uri to a cofing file?
