### ISSUE TITLE
提供一份编译好的0.9.2版本

### ISSUE THREAD

**Issue by Chandler-Lu** [Cenmrev/V2RayX#75]
### 版本号0.9.2(3)
![wx20180331-080738](https://user-images.githubusercontent.com/18322610/38157552-9ab25458-34ba-11e8-98d3-ea0bdd6f08aa.png)

### 使用源码
[v0.9.2](https://github.com/Cenmrev/V2RayX/tree/v0.9.2)

### 修改内容
作者源码中使用的v2ray-core版本为v3.10，我改用了最新的[v3.15](https://github.com/v2ray/v2ray-core/tree/v3.15)，除此之外未做任何修改
![wx20180331-081237](https://user-images.githubusercontent.com/18322610/38157635-4c6725de-34bb-11e8-8806-362eb74eb149.png)

### MD5
MD5 (V2RayX.zip) = D7969F5463FCBE1C2409C66F1D898D63

### 其他
1. 感谢作者对v2ray for mac图形界面的开发
2. 我不是做Mac开发的，无法解决其他问题，有问题请向原作者反馈

### 软件
[V2RayX.zip](https://github.com/Cenmrev/V2RayX/files/1865036/V2RayX.zip)

**Comment by seven76six** [comment]
非常感谢！等的就是这个！

**Comment by ReStiller** [comment]
作者在手动更新core中提到，[manually update v2ray-core](https://github.com/Cenmrev/V2RayX#manually-update-v2ray-core) 兼容性不能保证，请问您对您提供的版本体验过了吗？

**Comment by ddqp** [comment]
谢谢

**Comment by sn20110327** [comment]
十分感谢！

**Comment by Chandler-Lu** [comment]
@ReStiller  在我看来这件事情应该是这样，当gui版本固定时，生成的config和调用core的方法是固定的，也就是说万一v2ray-core修改了某个配置参数的配置方法，将导致config不匹配。再一个就是纯粹防止高版本core自身不稳定。
从3天前我发这个开始到现在，在我使用范围中没有出现过问题。
其实我发这个纯粹是想试试怎么做编译而已23333，如果gui没有本质的升级，一味升级core其实没有太大意义～

**Comment by Chandler-Lu** [comment]
@sn20110327 其实很简单
1. terminal键入以下命令：git clone --recursive https://github.com/Cenmrev/V2RayX.git
2. 找到V2RayX.xcodeproj，使用Xcode打开
3. 修改你需要改动的内容（比如版本号，比如所使用core的版本等等）
4. Build
> 需要注意的是，如果你不是在路由等设备上进行梯子的部署，建议在build前对terminal配置代理（自行查找配置方法）。因为编译过程中需要git clone v2ray-core的源码，如果terminal没有被配置代理，在这个网络环境下可能导致下载失败，编译终止

**Comment by bearbearhj** [comment]
十分感谢楼主，对于服务器内核升级后，mac客户端无升级导致无法连接的mac小白简直是救星！！！

**Comment by Chandler-Lu** [comment]
@bearbearhj 这俩没关系吧，而且升级mac客户端只需要手动升级core就行了

**Comment by bearbearhj** [comment]
对于没技术的小白来说换core有难度，希望授之以渔🙏

**Comment by Chandler-Lu** [comment]
@bearbearhj 不是我说啊，换core有难度。。复制粘贴也该会吧，[这里](https://github.com/v2ray/v2ray-core/releases)下载最新的macOS版的core，然后换掉/Applications/V2RayX.app/Contents/Resources下的v2ray和v2ctl即可。另外如果你不是自己搭建的v2ray就不要追新了，server和client的版本不一样有不兼容的可能

**Comment by bearbearhj** [comment]
@Chandler-Lu 秒懂，十分感谢！

**Comment by Chandler-Lu** [comment]
@Cenmrev 请把这个issue关掉吧～谢谢
