### ISSUE TITLE
Question and Suggestion

### ISSUE THREAD

**Issue by Voleking** [Cenmrev/V2RayX#8]
1.目前是否是不支持配置文件配置，那么 add Serves 之后配置记录在哪里
2.状态栏上参考 Surge 调宽一点可能会好看许多
<img width="293" alt="screen shot 2017-01-26 at 22 56 57" src="https://cloud.githubusercontent.com/assets/13161779/22335960/9ed7dcec-e41b-11e6-9f85-7be09f35612f.png">

**Comment by Cenmrev** [comment]
1. 是的，不支持自定义配置文件，每次启动时程序会生成配置文件。add Serves 以后的配置保存在 `~/Library/Preferences/cenmrev.V2RayX.plist`，你也可以通过命令行 `defaults read cenmrev.V2RayX` 来查看。
2. “调宽”是指调大状态栏上图标所占的宽度还是指所给截图中菜单的宽度？前者的宽度我可以调整，后者的宽的是系统自动计算的。

**Comment by Voleking** [comment]
不知道为什么无法上传两张截图，菜单宽度是系统计算的么，好吧
