### ISSUE TITLE
下个版本是否能加入html2支持

### ISSUE THREAD

**Issue by lidfgab** [Cenmrev/V2RayX#80]
下个版本是否能加入html2支持，还是0.92版本已经支持html2了？

**Comment by Chandler-Lu** [comment]
html2是什么东西。。http/2吧。。

**Comment by lidfgab** [comment]
对对，http2支持~

**Comment by a13547** [comment]
最新的源代码已经支持HTTP/2，下载编译即可，我正在使用。

**Comment by ColeHou** [comment]
@a13547 请问怎么配置？没有找到

**Comment by a13547** [comment]
你下载好源码，编译完成了吗？

**Comment by Chandler-Lu** [comment]
@ColeHou 自己看commits就知道了，3天前作者push了新的更新，支持http/2。自己下载源码编译

**Comment by Chandler-Lu** [comment]
编译后是这样，如何编译我有写过：https://github.com/Cenmrev/V2RayX/issues/75
![2018-05-04 16 41 19](https://user-images.githubusercontent.com/18322610/39619358-2072376a-4fba-11e8-827c-fd6edf492e8d.jpg)

**Comment by ColeHou** [comment]
@Chandler-Lu ok，感谢

**Comment by ColeHou** [comment]
@Chandler-Lu 好奇怪，我编译好了但是使用http/2还是不能连通，关键还不知道哪里错了

**Comment by Chandler-Lu** [comment]
@ColeHou 两个问题，第一个，源码默认的v2ray-core版本是3.10，而支持h2的core版本是3.14+。所以你要手动升级core。第二个，你配置写的有问题

**Comment by Chandler-Lu** [comment]
@ColeHou 刚作者推送了一个新的更新，fix了开机丢配置的问题，core的版本也改过了，可以重新编译。
升级core版本有两个方法，第一个是修改源码的V2RayX/dlcore.sh这个文件头部的VERSION然后编译，或者手动下载core for macOS，然后替换掉已经编译完成的v2rayX目录下的Resources

**Comment by ColeHou** [comment]
@Chandler-Lu 我昨天是手动替换的，但是没有用，我马上试一下，感谢
