### ISSUE TITLE
使用V2ray Rules模式时部分国内网站走的是代理

### ISSUE THREAD

**Issue by a13547** [Cenmrev/V2RayX#82]
V2rayX 版本：通过最新的源代码编译，但之前使用过的三四个版本都有此问题。
现象：部分国内网站通过代理连接，如腾讯，搜狐等。单纯使用V2ray Core时无此问题。编辑config-sample.plist 添加 geoip 和geosites时似乎无效。

**Comment by Cenmrev** [comment]
能不能把你单独使用V2ray Core时能正确区分国内外流量的配置文件贴出来给我参考下呢？

**Comment by a13547** [comment]
{
  "inboundDetour" : [
    {
      "domainOverride" : [
        "http",
        "tls"
      ],
      "port" : 1086,
      "listen" : "127.0.0.1",
      "protocol" : "socks",
      "settings" : {
        "auth" : "noauth",
        "udp" : true
      }
    }
  ],
  "outboundDetour" : [
    {
      "protocol" : "freedom",
      "settings" : {

      },
      "tag" : "direct"
    },
    {
      "protocol" : "blackhole",
      "settings" : {

      },
      "tag" : "block"
    }
  ],
  "dns" : {
    "servers" : [
      "223.5.5.5",
      "8.8.8.8"
    ]
  },
  "inbound" : {
    "port" : 1087,
    "listen" : "127.0.0.1",
    "protocol" : "http",
    "settings" : {

    }
  },
  "outbound" : {
    "mux" : {
      "concurrency" : 8,
      "enabled" : false
    },
    "protocol" : "vmess",
    "settings" : {
      "vnext" : [
        {
          "users" : [
            {
              "id" : "",
              "alterId" : 0,
              "security" : "auto"
            }
          ],
          "address" : "",
          "port" : 443
        }
      ]
    },
    "streamSettings" : {
      "security" : "tls",
      "httpSettings" : {
        "path" : "",
        "host" : ""
      },
      "network" : "h2",
      "tlsSettings" : {
        "serverName" : "",
        "allowInsecure" : false
      }
    },
    "tag" : "proxy"
  },
  "policy" : {
    "levels" : {
      "0" : {
        "uplinkOnly" : 5,
        "connIdle" : 150,
        "downlinkOnly" : 10,
        "handshake" : 4
      }
    }
  },
  "routing" : {
    "settings" : {
      "rules" : [
        {
          "type" : "field",
          "ip" : [
            "geoip:cn"
          ],
          "outboundTag" : "direct"
        },
        {
          "type" : "field",
          "domain" : [
            "geosite:cn"
          ],
          "outboundTag" : "direct"
        }
      ],
      "domainStrategy" : "IPIfNonMatch"
    },
    "strategy" : "rules"
  }
}

**Comment by Cenmrev** [comment]
https://github.com/Cenmrev/V2RayX/pull/98
