### ISSUE TITLE
transport settings 无反应

### ISSUE THREAD

**Issue by Aperocky** [Cenmrev/V2RayX#89]
when I'm trying to set the transport settings for my second server, the GUI just dies - nothing gets changed either. It was slow when I set up transport settings for my first server, but at least it will pop up a setting screen - now it's just dies. To be more specific, I was trying to set TLS.

**Comment by Chandler-Lu** [comment]
Could you provide screenshots to tell the developer what's wrong happened. What version of V2rayX and your system do you use?

**Comment by Cenmrev** [comment]
Please back up all your server information manually, run `defaults delete cenmrev.V2RayX` in a terminal and try v2rayx again.

**Comment by Aperocky** [comment]
Hi Chandler:


I've resolved my problem, but I would like to follow up to your question. The problem is not always reproducible - The transport settings work mysteriously, which means it sometimes work and sometimes does not. And when it doesn't, no change happens in log, the GUI simply get stuck.


I'll come back with a screenshot and logs when the problem produce itself again - but this might not be for a very long time as the settings currently work fine.


Best.

Rocky

________________________________
