### ISSUE TITLE
[feature request] Add startup when system booted support

### ISSUE THREAD

**Issue by tinpont** [Cenmrev/V2RayX#9]

**Comment by Cenmrev** [comment]
Thank you for your suggestion.

Currently you can manually make V2RayX start when the system boots by opening System Preferences -> Users & Groups -> Login Items and adding V2RayX.app to the list. I will add the option in V2RayX's config window in the future.

**Comment by tinpont** [comment]
Thanks for your contribution, @Cenmrev !
