### ISSUE TITLE
恳请1.0.0的编译版本🙏 from Xcode零经验小白 

### ISSUE THREAD

**Issue by ImHUan** [Cenmrev/V2RayX#91]
如题，感谢🙏

**Comment by Chandler-Lu** [comment]
> V2RayX.app is built by running one of the following commands in your terminal. You can install this via the command-line with curl.
> sh -c "$(curl -fsSL https://raw.githubusercontent.com/Cenmrev/V2RayX/master/compilefromsource.sh)"
or step by step:
git clone --recursive https://github.com/Cenmrev/V2RayX.git
open V2RayX.xcodeproj and use Xcode to build V2RayX.

讲白了，输命令，或者，输命令，打开，build

**Comment by ImHUan** [comment]
@Chandler-Lu 兄弟，机器里没有 Xcode 啊，而且也不知道咋下载

**Comment by Chandler-Lu** [comment]
appstore免费软件

**Comment by mactrash** [comment]
@Chandler-Lu 

不是不想自已 build 

Xcode can’t be installed on “MacBook Air” because macOS version 10.13.2 or later is required.

**Comment by Chandler-Lu** [comment]
@mactrash 可以下载低版本xcode：https://developer.apple.com/download/more/?q=xcode

**Comment by ImHUan** [comment]
@Chandler-Lu  谢谢指教。低版本的哪个比较好？我是10.12

**Comment by mactrash** [comment]
@ImHUan 9.1 吧

**Comment by zitanjian** [comment]
1.0版本就编译下吧，毕竟99%的用户不会的，谢谢

**Comment by Chandler-Lu** [comment]
@ImHUan 9或者8的最后一个版本应该都可以

**Comment by vc1** [comment]
不是每个用户都是程序员

**Comment by vc1** [comment]
要不加个提醒，本工具仅供会编程的专业人士使用，普通用户勿用。省的浪费双方时间

**Comment by Chandler-Lu** [comment]
真不是我说话难听。。如果连安装xcode，输入一串代码都不会，只有两种情况，不是懒就是智商有问题

**Comment by afboyxiyang** [comment]
按步骤是可以成功的

**Comment by ImHUan** [comment]
@vc1   发现最新版Release里有编译好的版本了  https://github.com/Cenmrev/V2RayX/releases

谢谢作者 @Cenmrev

**Comment by mactrash** [comment]
谢谢作者 @Cenmrev
