### ISSUE TITLE
请问打算支持订阅吗？

### ISSUE THREAD

**Issue by tor9910** [Cenmrev/V2RayX#93]
目前 v2ray 手动配置起来非常麻烦，请问有打算支持订阅或者二维码配置吗？

**Comment by Chandler-Lu** [comment]
好像至今为止官方并没有提供标准的类似于ss://或ssr://的配置接口，目前提供二维码配置的v2rayN for win和v2rayNG for Android共用一个标准，shadowrocket for iOS自有一个标准

**Comment by Cenmrev** [comment]
如楼上所说，v2ray官方没有提供标准前，不打算支持。
