### ISSUE TITLE
V2RayX 新版

### ISSUE THREAD

**Issue by WinLinKer** [Cenmrev/V2RayX#95]
![image](https://user-images.githubusercontent.com/3109626/40487453-c38bbb2e-5f96-11e8-8aea-b0e13ba7bda7.png)

在使用 

![image](https://user-images.githubusercontent.com/3109626/40487476-dcead8d4-5f96-11e8-86d2-070b4e1ebd41.png)

There is no Internet connection
There is something wrong with the proxy server, or the address is incorrect.
Try:

Contacting the system admin
Checking the proxy address
ERR_PROXY_CONNECTION_FAILED

会出现上面的错误，之前的版本，我浏览器没有安装switchomega插件，就可以访问的，现在国内，国外都不行了

现在是能pac模式，麻烦作者看下

![image](https://user-images.githubusercontent.com/3109626/40487532-0bd241b4-5f97-11e8-962a-67602945d64d.png)

--------   Safari可以， Chrome 就出现问题

**Comment by Chandler-Lu** [comment]
没看懂你到底什么模式不行，pac模式下用SwitchyOmega干嘛？
开头写pac模式出错，下面又说“现在是能pac模式”。。

**Comment by WinLinKer** [comment]
@Chandler-Lu ,是这样的，可能没表达清楚，因为之前一直使用是  V2Ray Rules规则，一直能科学上网，今天编译了最新的版本，放上去，就发现 V2Ray Rules 不能使用，我才下载的 SwitchOmega，当我禁用SwitchOmega之后，选择pac，发现也是可以科学上网的，现在就是在pac模式下

**Comment by Chandler-Lu** [comment]
这个恐怕要问作者了，我这里rule和pac在safari和Chrome下没有问题的～

**Comment by zitanjian** [comment]
https://github.com/Cenmrev/V2RayX/issues/60#issuecomment-369531443
https://github.com/Cenmrev/V2RayX/commit/714329144a59743dbbdb16a65ff92a6ba4aff6fc
 V2RayX/AppDelegate.m
@@ -345,7 +345,7 @@ - (NSDictionary*)generateFullConfigFrom:(ServerProfile*)selectedProfile {
         fullConfig[@"dns"][@"servers"] = @[@"localhost"];
     }
     if (proxyMode == rules) {
-        [fullConfig[@"routing"][@"settings"][@"rules"][4][@"ip"] addObject:@"geoip:cn"];
+        [fullConfig[@"routing"][@"settings"][@"rules"][0][@"ip"] addObject:@"geoip:cn"];

看下编译的源码里最后一行是不是改了？

我直接改0.9.1的app包里的这个 V2RayX/config-sample.plist，出现和你类似的问题，PAC菜单项选不上

**Comment by WinLinKer** [comment]
现在只有pac模式能用，其他的都不行

**Comment by WinLinKer** [comment]
换回ssr了，懒得折腾了

**Comment by Cenmrev** [comment]
我这里重现不出来你的情况。既然你说“Safari可以， Chrome 就出现问题”，那逻辑上可以判定是 Chrome 或者 switchomega 的问题而不是 V2RayX 的问题。一种可能是switchomega的配置端口填错了。换回ssr是明智的选择。毕竟上网工具是服务于工作的，把本该工作和休息的时间用来折腾是不划算的。

**Comment by WinLinKer** [comment]
@Cenmrev ，谢谢作者回复，我重新编译了下，又可以了，但是pac模式又出现问题了，先用着吧。

**Comment by WinLinKer** [comment]
@Cenmrev ,刚用最新的代码，重新编译了一下，一切都正常了，谢谢作者
